### ISSUE TITLE
ODEXed gapps

### ISSUE THREAD

**Issue by eugenesan** [opengapps/opengapps#124]
I wonder is it feasible to create variant of ODEXed Gapps?
This can be useful in following cases:
1. ROM for devices with small and/or slow /data partition.
2. Faster first boot and faster initial boot (the one where user password is asked) on encrypted devices.

**Comment by mfonville** [comment]
It would be possible, but we'd first have to complete the AOSP build process integration. Then that process can pre-generate the ODEX versions of the APK.
Personally I would give this the very lowest priority though, because it would only be applicable to small sets of users (since you'd potentially have to make a different version per ROM) and it would mostly be useful for ROMs that would want to pre-bundle the GApps. Which is a practice that we know of that Google is not happy with...

**Comment by mfonville** [comment]
@Blystad could you check if this would be possible for the AOSP builds? Because this doesn't apply to this branch of code (anymore).

**Comment by Blystad** [comment]
I'm not 100% sure what ODEXing is...if it's pre-compiling the DEX files, then that's possible in AOSP using `WITH_DEXPREOPT := true` (this calls oat2dex and a lot of other commands. It ends up taking more space, but makes the initial boot time faster).

**Comment by eugenesan** [comment]
@Blystad Thanks, I am aware of this option in AOSP. I was talking about creating GAPPS package that would "fit" such a ROM variant, with apps being pre-optimized in it.

**Comment by mfonville** [comment]
But for the flashable package it would be impossible, because the classes.dex differs per ROM.
So the best way to do this, would be through the AOSP build system, to build it combined when building your ROM.

Does ```WITH_DEXPREOPT := true``` work on on the open gapps aosp too already?

**Comment by Blystad** [comment]
Yes - https://github.com/opengapps/aosp_build#dex-pre-optimization

Isn't classes.dex created on a per-application basis? Or is it linked to the existing boot.dex? I just find it a bit strange that there is such a tight connection between dex optimized applications, and the actual ROM.

That being said, I have encountered various dexopt issues when working on Lollipop ROMs...I've had to turn off dex preopt i engineering mode, otherwise it was a PITA to develop system apps.

**Comment by mfonville** [comment]
Well, I am no expert in these fields. So I can be completely wrong.
But I thought that the classes.dex "binary" form of an application depends on various aspects of the device/ROM, like CPU, framework and boot.oat/dex.

I thought that is also a reason why after updating a ROM, if there are invasive changes, you need to wipe your cache, to regenerate the applications' dex files.
