### ISSUE TITLE
Storage space reported incorrectly for f2fs-formatted partitions

### ISSUE THREAD

**Issue by moore-bryan** [opengapps/opengapps#129]
I fall into the "insufficient space" error crowd, but I believe I arrived there because of my selected partition format of f2fs; please advise.

**Comment by mfonville** [comment]
Please include the full debug log. And also post any details that would confirm your suspicion why the space calculations are wrong.

**Comment by moore-bryan** [comment]
I have /system, /data, and /cache formatted f2fs when I installed cm-12.1-2015-0926-UNOFFICIAL-by.temasek-manta.zip, UPDATE-AnyKernel2-khaon-kernel-manta-09-12-2015.zip, and open_gapps-arm-5.1-full-20151004.zip. Both CM and khaon kernel install correctly, but opengapps--all versions, BTW--fail with the "Error 70." 

Here are the logs; .tar.gz isn't supported in the hub... thought it was for some reason.
https://drive.google.com/file/d/0B873HXzujAoLRVRxajB0c21LQjg/view?usp=sharing

**Comment by mfonville** [comment]
Are you sure your recovery supports f2fs properly? Because the information reported by your recovery is that the partition is 817152KB and 633816KB is already used, and only 169000KB is available. The further calculations done by Open GApps with this information are correct.
So please inspect (from e.g. a file explorer) within your Android OS itself whether you *really* only have 169MB available, or that your recovery fails to detect this correctly.

**Comment by moore-bryan** [comment]
It claims to, at least. I've asked the developer to step-in and answer some of the "nuts-and-bolts" questions to which I don't have answers.

**Comment by mfonville** [comment]
Are there any updates, whether the space reported is really wrong?

**Comment by moore-bryan** [comment]
Sorry for taking so long to respond; life.

If I reformat the partition ext4 and then have TWRP "resize" it, I can
install BaNKs no problem, but not OpenGapps.

--
*B.Moore*

**Comment by mfonville** [comment]
You are aware that BaNKs contains much less apps, right?
You are at the moment trying to install the 'full' package, which is quite large. You only have 169MiB available, and install e.g. the micro package.

**Comment by moore-bryan** [comment]
I've tried all the packages offered by opengapps and pico and nano will
install, but won't allow me to update any apps or install new ones claiming
"no space."

**Comment by mfonville** [comment]
It is weird that they wouldn't allow you to update or install any new apps, since those would be on the /data/ partition and not on /system/.
Are you sure your device's partitions are in good shape and that your ROM and kernel fully support f2fs?

Also I do find it weird that your ROM is using a 600MiB, while most ROMs use around 500MiB, and that your /system/ partition is so small with just 800MiB. E.g. the /system/ partition on my GT-i9300 is 1.5GiB

I really think your ROM developer should step in and look at what causes your space issues, because for us it just plainly looks like you have to little space available, and what the cause of that is, is beyond our reach and scope.

**Comment by moore-bryan** [comment]
I'll try to get him involved... I'm certain the rom & kernel are f2fs
compatible, as they're both from khaon.

Thanks so much for your help!

--
*B.Moore*

**Comment by mfonville** [comment]
@moore-bryan do you have any updates? Because I don't know what we could further do to help, since we are just using the information provided by the recovery...

**Comment by moore-bryan** [comment]
Sorry, none... I'm pretty sure it has nothing to do with opengapps and is,
instead, a script issue with f2fs formatting.

Thanks for your follow-up and all your help!

**Comment by mfonville** [comment]
Ok, then I will close the bug :)

**Comment by moore-bryan** [comment]
Thanks, again, for all you assistance...
