### ISSUE TITLE
Random reboots when removing system apps

### ISSUE THREAD

**Issue by sampalmer** [opengapps/opengapps#131]
### Problem

Installing Open GApps caused random reboots on my phone. Android didn't even shut down; it just spontaneously restarted.

### When it occurred

* Typically after signing into the Google account during the initial setup wizard
* Also happened after skipping the Google account setup in the initial wizard and then going to the home screen
* Also happened when using Titanium Backup to restore app data (just data, not APKs)

### Setup

Phone: Sony Xperia M
Firmware: Cyanogenmod 12.1

### `gapps-config`

	BasicDreams
	Browser
	CalendarStock
	CMAccount
	CMAudioFX
	CMUpdater
	CMWallpapers
	Email
	FMRadio
	Galaxy
	HoloSpiral
	LiveWallpapers
	NoiseField
	Phasebeam
	PhotoPhase
	PhotoTable
	PicoTTS
	SimToolKit
	Themes
	VisualizationWallpapers
	WhisperPush

### Troubleshooting

I tried the following to narrow down the problem:

* CyanogenMod versions
  * cm-12.1-20150919-NIGHTLY-nicki
  * cm-12.1-20151003-NIGHTLY-nicki
* Performed clean install (wiped system, data, dalvik, cache, sd card)
* Open GApps
  * open_gapps-arm-5.1-full-20151003
  * open_gapps-arm-5.1-full-20151005
* The problem happened on one of my Xperia Ms but not the other. Don't know why. Maybe it's related to the Google account used to sign in since I use a different one for each phone.
* The problem didn't happen after removing the above stuff from the `gapps-config` file.

### Cause

I believe one of the stock apps I removed in the above `gapps-config` file caused the problem. Don't know which one.

### Workarounds

* Not installing Open GApps
* Not removing any apps via `gapps-config`

### Recommendation

In the wiki for advanced configuration (https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options), add a warning to the "Removal of Stock applications" section similar to the warning in the "Universal Application Removals" section so users like me won't think it's safe to remove these apps.

**Comment by mfonville** [comment]
Thank you for properly researching your problem before filing the issue. It is a very weird problem that this appears when removing these apps, since (with the exception of 'Themes') none of those are really integrated with the rest of the system. And personally I actually use all these removals too, on my GT-i9300, but never experienced the issue.

If the reboots happen so frequent, could you maybe attach a logcat to your system, trying to catch the error that triggers the reboot?

And could you maybe try with to pinpoint which removal triggers the issue. E.g. by removing half of the removals from the list, and checking if the reboots still happen? If they do, use the half of the list again, if they don't, use the other half and repeat. (So a binary search)

**Comment by sampalmer** [comment]
I've got one logcat dump filtered to Error logs only, but GitHub isn't letting me upload it. I might try again later.

I had a go at pinpointing which removal caused the problem, but unfortunately, I couldn't do it. The issue might be more intermittent/random than I thought, so I thought I'd narrowed it down to the bad removal, but the problem didn't happen.

That's about as much as I'm willing to troubleshoot since it's pretty time-consuming! Hopefully if someone else runs into the problem they can help narrow it down.

**Comment by mfonville** [comment]
You can try to upload the logcat as a gist maybe? Otherwise use Google Drive or Dropbox to share it with us. We can always take a look.

If it is hard to troubleshoot and we cannot find the exact cause/source of the problem I suggest to close the bug until we get more insights.

**Comment by sampalmer** [comment]
Good idea! I've uploaded it as a Gist here: https://gist.github.com/sampalmer/e8fb732eb751b04a24b3

From memory, that logcat dump was taken after a reboot crash happened during a Titanium Backup batch app data (not APK) restore.

Yeah, it's fine with me if you close the issue. To me, the main thing here is users are warned that they *could* have problems from removing the stock apps. I think it'd be useful to add such a warning to the wiki's [Removal of stock applications](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#removal-of-stock-applications) section. But it's your call, not mine. :)

**Comment by mfonville** [comment]
Thank you for the Gist. I took a look at it, but damn, what a loads of various errors appear. I really would have the suspicion that something under the hood was broken in that ROM, or that maybe restoring the data of the apps would have introduced some serious issues.

Aside from removing the Themes, I have had zero issues (and many other people too) and removing e.g. a wallpaper shouldn't be able to trigger this behaviour at all. So I will just keep the warning for the Themes entry.

The cat is mine ;-)

**Comment by monojp** [comment]
Hi, sorry for reviving this isse, just didn't want to create a new one. I had similar problems (exception after upgrading, sudden reboot, "bootloop" and broken Trebuchet config after multiple forced reboots) and it was the removal of Themes that caused this. Have also created a gist with the relevant logcat entries https://gist.github.com/monojp/beaee6d5b0c6cf6117f4

Maybe there is need for another warning or a more detailed one on the advanced settings page. Debugging this was tricky because I always thought the upgrade process or recent CM changes broke something.

**Comment by mfonville** [comment]
Thanks for your information @monojp !
I will add it to the wiki as extra info.
