### ISSUE TITLE
StockCamera removed although +CameraStock in .gapps-config

### ISSUE THREAD

**Issue by Sodivad** [opengapps/opengapps#136]
Hi i would like to report that my camera was deleted even though I included +CameraStock in my config.
Here is the log of my second attempt where I tried if +Camera would have the desired effect and only the Documentation was wrong. You can see it would have removed my stock camera if it would have been present. The first flash was clean (data wiped). 
I cant upload my log so here is a gist:
https://gist.github.com/Sodivad/0cc4ce43025e876ef733#file-open_gapps_log-txt

**Comment by rapperskull** [comment]
You need to provide the debug logs, otherwise we can't help you.

**Comment by Sodivad** [comment]
Here are the debug logs:
https://drive.google.com/file/d/0B6CU6g-V1x9dTjVLQnZaOFJiaTQ/view?usp=sharing

**Comment by mfonville** [comment]
I did review the debug log and looked at our installer.
And the conclusion is, IF googlecamera is to be installed, the stock camera is ALWAYS removed.
I also looked at the documentation at https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#removal-of-stock-applications and nowhere it is descrbied that +Camera or +CameraStock would be a processable option.
This is, because both cameras can conflict with one another. If you don't want the stock camera to be removed, you should not install the google camera.

I am sorry that we cannot help you, but the installer does show the intended behaviour.

**Comment by Sodivad** [comment]
Ok thanks anyway!
