### ISSUE TITLE
Femto package with ONLY Play Store (+ dependencies)

### ISSUE THREAD

**Issue by breversa** [opengapps/opengapps#155]
Hi,

Is there any plan to offer a femto package with ONLY the Play Store and its *required* dependencies, and NO contact/calendar sync ?

For privacy reasons, I actually don't want/careabout ANY other Google service, except the Play Store itself. Actually, if BlankStore (https://github.com/mar-v-in/BlankStore) or any other equivalent was functionnal, I would have no use for the Play Store. :-)

**Comment by mfonville** [comment]
Hi, such a package is not in the planning.

The problem for what you would want, is that the Play Store depends on Google Play Services, which handles pretty much anything related to any Google service on your device. So Google Play Services does e.g. provide afaik (most of the) sync services, and e.g. calsync and contactsync are I believe mostly wrappers (but we can't check, since we cannot see Google's code). Leaving them out might e.g. break functionality on the phone, but would not stop sending data to Google.

I think for your situation would be best to try to set up your phone once with GApps, store the Google Play & device ID. Then reinstall your phone, and use external tools like https://chrome.google.com/webstore/detail/apk-downloader/cgihflhdpokeobcfimliamffejfnmfii?hl=en to download your APKs manually using the earlier obtained IDs. Note that this conflicts with Google Play's ToS though, so it is your own responsibility.

I will mark the issue as "wontfix".

**Comment by breversa** [comment]
Thanks for your quick reply !

>Leaving them out might e.g. break functionality on the phone, but would not stop sending data to Google.

What do you mean by "would not stop sending data to Google" ? What I usually do after installing the pico package (with Calsync exclusion, so that's already something that can be removed) is manually remove several apk file, among them ContactSync (I can't remember the exact name at the moment)… and so far, it has worked pretty fine. So why not take them out of the pico package then ?

**Comment by mfonville** [comment]
Because Google Play Services, the essential background service that provides all account logic, would still be in place and for sure is still sending all your syncable data to Google.

We don't remove them, so that on aosp you can actually take advantage of being able to use your Google account in the aosp frontend applications.

**Comment by breversa** [comment]
>Because Google Play Services, the essential background service that provides all account logic, would still be in place and for sure is still sending all your syncable data to Google.

… except if I use features like CyanogenMod's Privacy Guard to prevent them from reading my contacts. Or is it pointless anyway ??

>We don't remove them, so that on aosp you can actually take advantage of being able to use your Google account in the aosp frontend applications.

That's why I suggested another package, not removing stuff from the current other packages. :-)

**Comment by mfonville** [comment]
Using Privacy Guard might help, but totally honest, I have no clue, because these apps are a black box and we can only see their behaviour and not their inner working.

We will not make such a package for the public because it would mean reduced functionality, while from privacy perspective we don't know if it works (imho, best would be to assume google play services grabs and sends everything you have to Google). But you could easily maintain a patch for the our code that removes calsync anc contactsync from inc.buildtarget.sh lists, and build your custom pico package :-)

**Comment by breversa** [comment]
Thank you for your hints ! I'll look forward into both BlankStore (there has been an update in october 2015 !) and also into inc.buildtarget.sh, though I don't know how to build a custom package yet. :-)

**Comment by Exaeta** [comment]
Hello. This is unconscionable. I don't want Google uploading or downloading data to my phone in the form of contact information.

**Comment by breversa** [comment]
Hum… the more I think about it, the less I understand why a "totally minimum Play Store package" should not be made.

To rebute the previous arguments againt :
1- "it would mean reduced functionnality" : well of course, that's the point : *minimum* functionnality, juste like each smaller package has less functionnality than the bigger ones.
2- "assume google play services grabs and sends everything" : though I agree with this statement, however, I can't see how removing components (i.e. contacts sync) would make it send *more* data to Google. What's more, one less background service = less resource usage, less bandwith, more battery (even if just a tiny amount).

Just for the record, here my .gapps-config file that I *think* makes the minimum features (according to the wiki) :
'''PicoGApps
 Exclude
 CalSync
 DialerFramework
 GoogleTTS
 PackageInstallerGoogle
''''
