### ISSUE TITLE
[AROMA] Allow UAR with extra file

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#171]
Is there a way to have the AROMA version read a config file for extra options?

Why when AROMA is supposed to avoid it for ease of use? Well, we could use it so advanced users that still use AROMA so they can select apps as they install; could still use things not in AROMA like Universal App Removals and any keywords not in the UI (due to nobody updating it or things that we shouldn't make visible like the force options).

The main issue I see is how do we make it where it ignores apps in the file if using AROMA? I suggest that since people using this would most likely know how the config works but still use AROMA, educate that only non-AROMA options should be in there (like UAR or force options). We also could only allow UAR [surrounded by ()] which while not letting you use the force options would be safer. The last way would be to use a special `.aroma-config` file which the installer only allows UAR/Options but not apps.

So, since it's the same installer powering it; could we make it where the AROMA version reads from a config in addition to the prop files?

@mfonville @raulx222 @opengapps/developers

**Comment by mfonville** [comment]
Hi Brandon, your text is a bit difficult to read, but I hope that I understand it correctly:
you want the Aroma installer to read extra options, that are not available from the Aroma UI itself, are read from an extra optional configfile?

If so, I do not see the real use of this, because imho Aroma is targeted at an audience that doesn't want to mess with config files at all. It would make little sense to use Aroma if you would already have the knowledge and skill to make your own config to use any of the advanced features.

**Comment by bgiesing** [comment]
@mfonville The reason I use (and I know some others); is not because ease of use or not knowing how to make a config file but instead because of the ability to select apps at install time.

With the text file, you have to edit it before rebooting into recovery or on a separate device. If the installer says you don't have enough space or you want to change your app selection, you then have to edit the file (which if you don't have a computer) means you have to reboot back into the device. If you just wiped to install a new ROM; that's kinda impossible. Also, if even if you didn't; it still would take forever to reboot back to remove/add one word. (Not to mention if that still isn't enough and you have to repeat again.)

But with AROMA right now, if I need more space; I just restart the installer and remove an app from the list.

With this config file, advanced users that still use AROMA for selective installing (and not ease-of-use), would still be able to use Universal App Removals. While it still is a text file (so still has the issues above), it wouldn't have to be edited as often (you make a list with your UARs and shouldn't have to update it again).

**Comment by mfonville** [comment]
I don't think power users that want to use the Universal Removal feature switch their "set of apps" that often, that they would be using Aroma instead of a simple change to their configfile. The use case is imho very exotic. Implementation would need quite a bit of new code which would have to be thoroughly tested, which is hard with Aroma.
That in combination with that I already have a list of issues that definitely need more attention at the moment (e.g. Android version-specific libs, AndroidTV) I don't think I will pursue this issue. I will accept PRs ofc.

**Comment by bgiesing** [comment]
Well this is how I have to do it as my computer no longer works, condig files are impossible to use when you have to edit it. And with all the apps I need, UAR are the only way to fit them.

**Comment by mfonville** [comment]
You can your easily edit your configfile from recovery, just open the command terminal and use e.g. busybox's built-in vi to edit the file.
