### ISSUE TITLE
Marshmallow 255 install failed

### ISSUE THREAD

**Issue by mrosel** [opengapps/opengapps#180]
Fresh install, cleared all data

Nexus 5, hammerhead D820(E)
Bootloader HHZ11h
Cyanogenmod 13 (Marshmallow), latest nightly(12/03/2015)
Recovery is cm-13.0-20151127

I've tried each open_gapps-arm-6.0-* with no success either via sideload or locally. The error is consistent "Install failed": 
--Install /data/media/0/open_gapps-arm-6.0-nanopp....
:E Installation error in /sideload/package.zip (status 255) 
Installation aborted.

The logs show the exact thing. 

curious if the issue is related to this:https://github.com/opengapps/opengapps/issues/53
Should this work with CM or is TWRP absolutely required?

**Comment by mfonville** [comment]
It should work with CM Recovery too (though it is best-effort, since it lacks functionality compared to TWRP).

The only error 255 I find about CWM (on which CM Recovery is based) is that update-binary would be incompatible. So either the zip is damaged (during download, or when transferring to device) or something else weird is happening.

It ain't possible to debug this easily, since the recovery itself doesn't provide any extra information. So my suggestion would still be to switch to TWRP (which in generally is a good choice, since it is the only recovery in active development).

**Comment by mrosel** [comment]
That was too easy. Just fastbooted TWRP and sideload worked as expected.

Thanks for the quick reply.

**Comment by mfonville** [comment]
no problem. Happy your issue got resolved!
PS: todays opengapps has some potential issues if you don't install Google WebView, so use a large package or wait a few hours for the next release ;-)

**Comment by shuhaowu** [comment]
I can confirm this happens on CM-recovery. For those of us that doesn't want to move to TWRP, can this be looked at more?

**Comment by mfonville** [comment]
Actually it is fixed already in our source, it was caused by CM not accepting the /usr/bin/ash shebang. But there is only an updated build triggered when new Google APKs arrive, which will probably be after the Christmas holidays.

So either you can manually adjust in update-binary the first line to /usr/bin/sh or wait a few days for a new build.

**Comment by alwinpietersen123** [comment]
When trying to install an adjusted version of the gapps, with the /usr/bin/ash replaced by /usr/bin/sh in the update-binary, I get the error: 'Footer is wrong. Signature verification failed'. Is there a way to install this adjusted version of gapps in CM-recovery?

**Comment by mfonville** [comment]
I will force an updated arm build coming night. That should resolve your issues.
CC @NicholasBuse (so that you'll know you are free to update ARM apps ;-))

**Comment by alwinpietersen123** [comment]
I tried installing the new version of gapps, but now I get the message: 'Installation error in /sideload/package.zip (Status 1)'. What does this error mean and how can I resolve it?

**Comment by lapism** [comment]
I was trying to install NANO package and I got same Status 1 like alwinpietersen123. ROM CM 13 for Nexus 4.

**Comment by mfonville** [comment]
Status 1 seems to be caused by toybox not having implemented remount as an option: https://github.com/opengapps/opengapps/issues/210

**Comment by lapism** [comment]
And what I should do with that ? :)
