### ISSUE TITLE
manual install (.apk) can't from zip

### ISSUE THREAD

**Issue by roberto68** [opengapps/opengapps#185]
For some reasons I've to install manually.... I extracted all the .apk files but still doesn't work. there are also some folders beside the .apk files. Do I have to put those folders  (at least those with those not empty one with binaries .ini...) to folder where I have the .apk files (cause they seem to be kind of dependencies - those fies in folder)

**Comment by mfonville** [comment]
You cannot install these APKs manually since the libraries are stripped from the APK files.

Also I have no clue what you are trying to do, but what you describe doesn't really belong in the scope of our installer and are not really an "bug" for the project. I suggest to try out the XDA forums to ask for more help.
