### ISSUE TITLE
Add support for excluding Google Contacts Sync

### ISSUE THREAD

**Issue by GermanKiwi** [opengapps/opengapps#190]
Could you kindly add a keyword for the Google Contacts Sync Adapter, so that it can be excluded from installation via gapps-config? (Similar to `CalSync` for the Calendar Sync Adapter).

I use an Office 365 account for my contacts, and therefore don't sync my contacts to my Google account - so I don't need to have the Google Contacts Sync Adapter running on my phone (right?)

**Comment by mfonville** [comment]
https://github.com/opengapps/opengapps/issues/155

Has been answered before, we won't implement it like this at the moment because to our information the contactssync is a wrapper and we don't want to give false illusions and/or broken implementations.
We might revise this in the future or if things are different on more recent Android versions.

**Comment by GermanKiwi** [comment]
Thanks for the explanation. I couldn't find any previous issues on this topic when I searched.
