### ISSUE TITLE
Download failures

### ISSUE THREAD

**Issue by dsalt** [opengapps/opengapps#193]
I'm seeing repeated download failures. They seem to occur after a random time, with the minimum amount downloaded being around 80MB. Download speed is around 190MB/s (which is about the maximum for my 'net connection); Iceweasel via squid.

If I could use wget to fetch the files – referrer needed? – I could probably do a complete fetch in several parts.

**Comment by mfonville** [comment]
I'd urge you to write about download failures to GitHub, since they provide the hosting of our releases. Then they can ask Amazon Web Services (their physical hoster) to fix it.

You can use wget, to see the URLs of all packages and releases I point you to https://github.com/opengapps/arm/releases (see the other repos for other architecture's releases).

Btw, for next time it is better for the workflow to ask such questions on our XDA forum instead of direclty opening an issue here, since we use issues to keep track of bugs and features.
