### ISSUE TITLE
add_sourceapp.sh should discard the old APK, when the API level is updated, if the new API is <= 19

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/opengapps#20]
I believe that add_source.sh has an issue around determining where the "existing" apk is. I believe that it assumes that the API is the same as the one we are adding.

This isn't a huge issue, we just keep stale apks in the repo.

**Comment by mfonville** [comment]
If the API level is updated, it keeps an old version around of that lower API level, so that packages can be build for as much API levels as possible.
Is that the behaviour you are seeing?

**Comment by NicholasBuse** [comment]
Yes, but if both API levels are <=19, what is the point of keeping the old?  Also, I think we ran into the opposite case with your latest commit removing Hangouts for 5.1. Maybe?

**Comment by mfonville** [comment]
Yes, I could indeed automatically remove the ones that are <19. But I am not going to code that in now, it doesn't have priority.
For the Hangouts removal of 5.1, luckily my scripts always select the 'latest' version, so it didn't impact which Hangouts version was packaged. But I removed it manually, since that Hangouts version was (I believe to be) kind of unofficial and only released for some (beta testing for?) Project Fi. All latter versions of Hangouts were the lower API level again.

**Comment by mfonville** [comment]
This is now fixed. Clean-up is performed if you add a <=19 API level apk. All lower API versions are automatically removed.
THIS ASSUMES THAT NEWER API LEVEL IMPLIES ALWAYS A BETTER VERSION OF THE APP AND THAT THE API LEVEL WITH NOT DROP WITH NEWER VERSIONS.
