### ISSUE TITLE
Inbox by Google in the Aroma Package?

### ISSUE THREAD

**Issue by legendtang** [opengapps/opengapps#202]
Since many users choose to replace Gmail by Inbox, Gmail has been becoming a redundant one if they do not use SMTP / Exchange service, etc.

**Comment by simar7** [comment]
+1 to this. What would we need to implement this? I can help write a diff for this.

**Comment by mfonville** [comment]
Since Inbox is not bundled with any of the Nexus ROMs we don't have an 'official' path of where it should be stored in /app/ or /priv-app/.

The plan is to allow the building of "add-on"s (which could then also be included in e.g. Aroma) that could provide non-Nexus apps as Inbox.

I do need to make some infrastructural changes to the building and packaging process, and some other changes to those take priority at the moment.

**Comment by jhedfors** [comment]
Is there still consideration of adding the ability of installing this via OpenGapps? 
I see some activity here:
https://github.com/opengapps/arm/commit/03f619342024dffca795bed9ee082ec0deea3969?utm_source=dlvr.it&utm_medium=twitter#diff-cbe6154b72b59f351e916990b999a364

**Comment by nezorflame** [comment]
@mfonville this should be closed now since Inbox is pretty much dead now.
