### ISSUE TITLE
Unable to upload updated source

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#21]
I am getting the following error when trying to upload the latest source. I followed exact commands listed on the front page for adding sources

~/opengapps/sources/arm$ git push
ERROR: Permission to opengapps/arm.git denied to DJAlik.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mfonville** [comment]
Hi, that is because I did not add you yet to the group with upload rights for the repo. I will add you to it.

**Comment by DJAlik** [comment]
Still can't upload new source

jalik@djalik-VirtualBox:~/opengapps$ ./add_sourceapp.sh /home/djalik/Downloads/com.google.android.apps.docs.editors.docs-1.4.232.10.35-52321035-minAPI14.apk 
Importing Docs
Package com.google.android.apps.docs.editors.docs | VersionName 1.4.232.10.35 | VersionCode 52321035 | API level 14
Native code for architecture(s): armeabi-v7a 
Existing version sources/arm/app/com.google.android.apps.docs.editors.docs/14/52321030.apk
Replaced with sources/arm/app/com.google.android.apps.docs.editors.docs/14/52321035.apk
djalik@djalik-VirtualBox:~/opengapps$ cd sources/arm
djalik@djalik-VirtualBox:~/opengapps/sources/arm$ git add *
djalik@djalik-VirtualBox:~/opengapps/sources/arm$ git commit
[detached HEAD 3d25e8e] New Docs 1.4.232.10.35
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename app/com.google.android.apps.docs.editors.docs/14/{52320935.apk => 52321035.apk} (89%)
 mode change 100644 => 100755
djalik@djalik-VirtualBox:~/opengapps/sources/arm$ git push
To git@github.com:opengapps/arm.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:opengapps/arm.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by mfonville** [comment]
That is because the git branch you are working on, is behind the latest version that is online. Nicholas also pushes a lot of new APKs as soon as they are on apkmirror.com

Also you have to make sure your git head is attached to the one of the remote repository. I recently made some changes to download_sources.sh which should resolve the problems around this issue.
You might solve the problem by first checking out the master branch with 'git checkout master' in the directory of the sources you are trying to update (so in this case sources/arm)

I urge you to read about the challenging issues concerning git, submodules and the HEAD. It is not easy and I also need sometime to grasp it fully and fix my workflow. You might also want to get in contact with @NicholasBuse if you keep finding issues, he is much more neat in the git management than I am.

Some sources to read:
http://www.vogella.com/tutorials/Git/article.html#submodules
http://komodoide.com/blog/2014-05/git-submodules/
http://git-scm.com/docs/git-submodule

Also look at what download_sources.sh contains and executes for you and compare that to the documentation.

**Comment by NicholasBuse** [comment]
> he is much more neat in the git management than I am.

ha! yeah right... :-) (This project has been most of my little experience with Git)

basically I do what @mfonville said and update my sandbox before trying to add anything.

in main opengapps:
```
git checkout master
git pull
```

from here the script, download_sources.sh, should get you up-to-date:

```
./download_sources.sh
```

historically I have had issues with detached heads (not master) with this, but @mfonville should have resolved it with recent update, but I have not tried yet. Historically I have done the following to ensure all 4 source project are current too:
```
git submodule foreach "git checkout master && git pull"
```
