### ISSUE TITLE
Project Fi/Tycho needs system app permissions

### ISSUE THREAD

**Issue by skylerbunny** [opengapps/opengapps#221]
In fairness, this is a pretty recent discovery; Tycho needs full system permissions to do its Thing.

See:

https://productforums.google.com/forum/#!topic/project-fi/d3jILa7bQR8
http://forum.cyanogenmod.org/topic/119798-project-fi/#entry563767
http://forum.cyanogenmod.org/topic/119798-project-fi/#entry566566

https://github.com/opengapps/opengapps/blob/a2ae5ecca8f951ec504653a4831806e8605dfef1/scripts/inc.buildtarget.sh#L242 shows that Tycho/Fi is not being installed with system permissions (IE, in system/app or system/priv-app when opengapps packages are built, and it needs to be for full functionality.

**Comment by Lrs121** [comment]
The question then becomes whether it would be better put within app or priv

**Comment by skylerbunny** [comment]
I wasn't sure, and that's why I wanted to bring it up. There seems to be ambiguity on that point.

**Comment by Lrs121** [comment]
Probably safe to start with just system/app and then go from there. Ill run a zip off and test it when i get home. That may fix the crappy service/switching ive been experiencing lately.

**Comment by skylerbunny** [comment]
As I understand it, if you are on Fi, 'the app not having system privs' will prevent switching to the other network. You will always be on 'the last network you were on when 'the last phone you were on had system permission to switch networks'.

Found these dialer codes linked from one of the posts, which may be helpful to verify 'before' and 'after' locations for the app. https://productforums.google.com/forum/#!topic/project-fi/IkOy8ZGNyPk

**Comment by Lrs121** [comment]
not really, with 5.x that may have been the case but so long as it has permissions on 6.x its allowed me to switch networks. Also it appears to be installed to system/app by default. 

Ive been running self made omnirom 6.0.1 builds using opengapps and looking in the system/app directory shows a directory for Tycho. I dont know if its the opengapps package or if theres a build flag for it with omnirom but its where its supposed to be.

If that is the case where its a build flag/patch from omnirom moving it to system/app when the tycho app is detected then changing the opengapps packaging to install it to system/app (or priv if that works better) by default may be recommended.

**Comment by Lrs121** [comment]
I forgot to mention it switches just fine it just tends to choose the worst network or technology eg. Choosing tmo edge when sprints lte is available.

**Comment by mfonville** [comment]
Hi,

the Super-package (and Aroma) contain projectfi and it is installed in app/Tycho, since that is also the location where Nexus ROMs install it. In general the difference between app and priv-app permissions is also very minimal since Android 5.

I think the switching is very probably done by GCS and not by Tycho, since I believe Tycho is only a frontend and GCS provides the backend. GCS is installed priv-app/GCS in the Super-package (and Aroma) if correct.

Take note that **if** you do not install GCS, that Tycho won't be installed by OpenGApps either, since it depends on it.

I read somewhere that to use Fi you do need to install the Google Dialer, but I don't know whether that is true.

Unfortunately I cannot do any testing myself since I don't live in the states. But if you could give me any feedback if anything should be changed, please let me know.
If nothing needs to be changed then please close the bug. (And we can always re-open ofc)

**Comment by Lrs121** [comment]
Ah makes sense, especially with GCS. 

As for needing Google Dialer, I think it may depend on the rom. Some roms have patches from the Pure Nexus Project rom. They figured out whats needed to get Fi working with AOSP roms. 

OmniRom, CyanogenMod (I think), and probably some others, have the patches or some sort of work around that fix switching. so long as the dialer and Tycho have proper permissions.

**Comment by ciwrl** [comment]
FYI - as of N it appears Tycho also needs priv-app (or is otherwise missing a sysconfig setting). 

`02-01 23:18:25.845  6444  6507 W BroadcastQueue: Permission Denial: receiving Intent {
act=android.intent.action.PHONE_STATE flg=0x10 (has extras) } to
com.google.android.apps.tycho/.receivers.PhoneStateReceiver requires android.permission.READ_PRIVILEGED_PHONE_STATE
due to sender android (uid 1000)
02-01 23:18:29.219  6444  6507 W BroadcastQueue: Permission Denial: receiving Intent {
act=android.intent.action.PHONE_STATE flg=0x10 (has extras) } to
com.google.android.apps.tycho/.receivers.PhoneStateReceiver requires android.permission.READ_PRIVILEGED_PHONE_STATE
due to sender android (uid 1000)`

**Comment by mfonville** [comment]
@ciwrl you checked the permissions that were granted to the app itself I assume?

**Comment by mfonville** [comment]
I now checked on the latest Marlin image, and the Tycho apps is in `/app` and there are only the trivial and already applied tycho entries in `/etc/sysconfig`

**Comment by ciwrl** [comment]
I'll run some additional tests here over the next couple of days (I have Fi enabled bullhead and angler) and confirm what I was seeing. 

Thanks for the quick response
