### ISSUE TITLE
explaination on wiki for PackageInstallerGoogle option?

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#227]
I have no idea what the reasoning was behind this.  I think it causes me bootloops with CM13, though.

What is it?  Is it replacing an AOSP package?  Was it not optional prior to becoming an optional thing- i.e. was it a core type package?
I'm not concerned in a paranoid sense.  I just don't know what it's advantages/disadvantages are and what it's reasoning for now being an optional package.
Is it a dependency of the option to submit suspicious apps to Google?  No idea but that's my only assumption.

**Comment by bgiesing** [comment]
@jawz101 Read #223, it explains the options and what changed recently with it.

But to answer some of your questions:
1. It is replacing an AOSP package. It's the screen that shows up when you install an APK outside GPlay
2. See issue above for that
3. Nope, that's through Google Play services.

**Comment by mfonville** [comment]
@bgiesing thanks for answering :-)

The exact advantages over the AOSP package are unknown, since it is proprietary and we have no access to Google's sourcecode ;-)
What we *do* know is that it does come with all of the Open Handset Alliance's ROMs and as such should be considered a core feature that fulfills *some* role. Moving it from core to pico was described in the PR to allow them to exclude the install using a keyword, for those who did experience issues with it.

Please feel free to write a page about this app on our wiki (I myself lack the time), and to link from the various existing pages to it. We could collect there some of the knowledge that *is* available.

If you don't mind I close the bugreport and let you free to decide on the follow-up :)

**Comment by jawz101** [comment]
Thanks, folks.  I figure it needs a write-up.  If I can wrap my head around what it does I'll put something out there.  It kinda doesn't make sense yet :)

**Comment by wadpasu** [comment]
#227

**Comment by ononoman** [comment]
#228
