### ISSUE TITLE
How can I get gapps for my Android 4.3 ?

### ISSUE THREAD

**Issue by yang-le** [opengapps/opengapps#244]
Hi,

Your scripts is cool.
But seems it only support Android 4.4+.
Which script should I modify to support my poor Android 4.3?
Cause I'm not so familiar with your magic scripts, help wanted, Thank you.

**Comment by mfonville** [comment]
Hi,

unfortunately I cannot (because of lack of time) help you in detail, because the Android 4.3 install base is really small, it ain't worth the effort for us as project members.
I will point you in the general direction:
* You will need to adjust files like build_gapps.sh to let it recognize and handle API level 18. E.g. you will need to make a new line at https://github.com/opengapps/opengapps/blob/master/scripts/build_gapps.sh#L49 but also through some of the other files like the Makefile.
* You will need to deodex the necessary core APKs from a Google Nexus stock image (you cannot do that with our tools, you need to use seperate tools for that).
* You will need to add the deodexed (and possibly other apps too) that are compatible with API level 18.

If you need any more help with that I would suggest to you to ask help in the XDA forum.
