### ISSUE TITLE
google packageinstaller is installed while stock one is not removed

### ISSUE THREAD

**Issue by cstkingkey** [opengapps/opengapps#252]
K3 note 6.0 rom
the stock one is "packageinstaller" rather than PackageInstaller

**Comment by mfonville** [comment]
That is a the K3 note stock ROM I assume? not the AOSP/cyanogenmod?

**Comment by cstkingkey** [comment]
Yes

**Comment by mfonville** [comment]
Ok, located in /app/ or /priv-app/ ?
Normally we don't do these kind of non-standard things for stock ROMs (they are best-effort and all very different) and for these situations normally the Universal Removal feature should be used.
But since this path is so close to the original we can make an exception.

**Comment by cstkingkey** [comment]
/priv-app/

**Comment by cstkingkey** [comment]
I'm using pico, so google should not be installed at first place, right?

**Comment by mfonville** [comment]
It is part of pico, originally it was even part of core (but we pulled it out of core, so that people can use a keyword whether they want it or not, because it gave issues on a particular ROM)
