### ISSUE TITLE
[Samsung S2 i9100, CyanogenMod 13.0] Need GApps package smaller than 50MB

### ISSUE THREAD

**Issue by piotrek1543** [opengapps/opengapps#255]
Hi,

I've already installed the latest CyanogenMod ROM: https://download.cyanogenmod.org/?device=i9100
for my device, but I cannot install opengapps [Pico version] as this package is too large for my device.

Before, I used to use opengapps Pico on CyanogenMod 12.1 ROM and that worked fine. Well, I cannot use another GApps package not provided by you as yours Pico package is the smallest one I've already seen.

I really like an idea of Aroma Graphical Installer, but this package is so huge. Is it possible to make an Aroma graphical installer, but in online version. I mean after I connect successfully with my WiFi network, I can choose using this installer which parts of GApps I want to install.

I tried also install Google Play Services and Google Play Store by APK, but version from 20th of January, which I'd found is unusable, as it crashes a lot. 

Could you help with this problem?

Cheers

**Comment by mfonville** [comment]
Google Play Services is 50MiB and you can't have any GApps without it.
Maybe you can re-partition the device? Otherwise I don't see any possibility for you than e.g. using an older Open GApps package where Play Services was still smaller.

The online-Aroma selection as you described has popped more than once in my mind (and of others too) but is unfortunately not possible. The zip-package as a whole file needs to be signed using a special tool. So unless we could do this in javascript (and we can't and if we would want that is *REALLY* hard, because first someone would have to port our dependencies like Openssl to javascript and that ain't gonna happen) that is not simply possible.

Google Play Services and Play Store have some issues in their last versions, but Google seems to be aware of them so I expect updates soon.

A tip for next time: please ask these questions on our XDA forum, they are better place for such discussion, make the knowledge better available to the community, more people are able to answer (and than I can put more time to developing instead) and keeps our bugs/issues better organized.

**Comment by piotrek1543** [comment]
ok, thanks

**Comment by piotrek1543** [comment]
Ok, next time I would use XDA forum, but could you tell me how can I install only Google Play Store. I mean - how to customize gapps-config to install only Google Play Services.

Yes, that's a pity that Aroma online installer is nowadays impossible to do.

**Comment by mfonville** [comment]
With gapps-config you can't exclude any of the "Core" applications.
You could remove the Core applications you don't want from the Core-folder in the zip; which prevents them from being installed. (and it destroys the valid signature; but if you use TWRP you can choose to ignore the signature fail).
I wouldn't recommend this though, since Google's apps expect all of these apps to be there, so you could get nasty crashes if hitting e.g. the Feedback-button in an app.

**Comment by piotrek1543** [comment]
Ok, I've already found that I have 66MB on my device's System partition. I would try to install older openGApps version from October 2015 (it has 64MB).

No, I cannot use TWRP as it not support my device. I had CWM based recovery but CM13 changed to stock recovery where I cannot toggle signature verification.

I need only Google play Services and Play Store. Well if I would find a solution I would tell it about on XDA. Nowadays, thanks for your help and nice explanation of that situation.

Cheers

**Comment by mfonville** [comment]
You can replace the CM recovery (within CM's settings you can disable the functionality that it automatically installs/replaces your recovery with CM's version).
Hope to see your on XDA, hopefully you can share your experiences with other S2 owners.

**Comment by piotrek1543** [comment]
Well, thanks, but I think it's impossible to install GApps as Pico package needs to have doubled free space

```
# Begin Open GApps Install Log
-----------------------------------------------------------------------------
           ROM Android Version | 6.0.1
                        ROM ID | cm_i9100-userdebug 6.0.1 MMB29U 5b3bf7d8a2 test-keys
                   ROM Version | 13.0-20160209-NIGHTLY-i9100
               Device Recovery | 
           Using Bundled XZdec | false
                   Device Name | GT-I9100
                  Device Model | GT-I9100
                   Device Type | phone
                    Device CPU | armeabi-v7a,armeabi
               getprop Density | 240
          default.prop Density | 240
            build.prop Density | 240
          Display Density Used | 240dpi
                  Install Type | Clean[Data Wiped]
     Google Camera Installed¹ | Clean
         FaceUnlock Compatible | true
      Google Camera Compatible | true
     New Camera API Compatible | false
         Current GApps Version | No GApps Installed
         Google Camera version | Legacy
      Installing GApps Version | 20160208
         Installing GApps Type | pico
                   Config Type | 
            Using gapps-config | Not Used
     Remove Stock/AOSP Browser | false[NO_Chrome]
      Remove Stock/AOSP Camera | false[NO_CameraGoogle]
       Remove Stock/AOSP Email | false[NO_Gmail]
     Remove Stock/AOSP Gallery | false[NO_Photos]
    Remove Stock/AOSP Launcher | false[NO_GoogleNow]
     Remove Stock/AOSP MMS App | false[NO_Hangouts]
    Remove Stock/AOSP Pico TTS | false[default]
        Ignore Google Contacts | false
        Ignore Google Keyboard | false
Ignore Google Package Installer | false
         Ignore Google NFC Tag | true[NoRemove]
         Ignore Google WebView | false
                     SwypeLibs | 922 (KB)
        Total System Size (KB) | 516040
        Used System Space (KB) | 453544
       Current Free Space (KB) | 62496
Additional Space Required (KB) | 54430       << See Calculations Below
-----------------------------------------------------------------------------
                  ¹ Previously installed with Open GApps
# End Open GApps Install Log

INSTALLATION FAILURE: Your device does not have sufficient space available in
the system partition to install this GApps package as currently configured.
You will need to switch to a smaller GApps package or use gapps-config to
reduce the installed size.


# Begin GApps Size Calculations
-----------------------------------------------------------------------------
  TYPE  |         DESCRIPTION        |      SIZE |   TOTAL
        |         Current Free Space |     62496 |   62496
 Remove |             Existing GApps | +       0 |   62496
 Remove |             Obsolete Files | +      24 |   62520
 Remove |      packageinstallerstock | +    1880 |   64400
Install |                     Core² | -   81514 |  -17114
Install |                  calsync³ | -    1244 |  -18358
Install |                googletts³ | -   24800 |  -43158
Install |   packageinstallergoogle³ | -    2056 |  -45214
        |             Buffer Space² | -    9216 |  -54430
-----------------------------------------------------------------------------
                      Additional Space Required |   54430
-----------------------------------------------------------------------------
              ² Required (ALWAYS Installed)
              ³ Optional (may be removed)

# End GApps Size Calculations

# Begin User's gapps-config

# End User's gapps-config
```
