### ISSUE TITLE
Should I fork a new project?

### ISSUE THREAD

**Issue by cirelli94** [opengapps/opengapps#264]
Hello, 
I was thinking to make a similar project with a stack of apps from https://f-droid.org/ to build an easy to install *.zip package.
I know this is released via GNU GPL, but i thought it was better to ask you.. Should I do this? Is not a problem to you?
Thank you

**Comment by mfonville** [comment]
Hi @cirelli94,
thanks for asking, it is much appreciated to consult :-)
The project is indeed licensed under GPLv3 (with "installable zip exception") so you are free to fork under that license.
It is important that your fork also adheres to the GPLv3 as it is a derivative work and attribution to the original Open GApps should be included.

It is possible to fork the project to wrap other apps than the gapps into an installable zips, e.g. I was already contacted by somebody who wanted to make a Sony-apps variant.
The best approach would be to fork the main opengapps repository and adjust the scripts to your needs. Also map the sources/*-directories to other submodules that contain the relevant APK resources you'd like to use.

Not required but much appreciated is a reference to opengapps.org; since our project benefits from word of mouth.

If you have any questions, please let me know.

PS: I do have plans to also start our own "fork"/variant under the opengapps banner for the MicroG project which is also hosted on f-droid; see #215
