### ISSUE TITLE
Missing checksum file: open_gapps-arm-5.1-super-20160313.zip.md5

### ISSUE THREAD

**Issue by CheyiLin** [opengapps/opengapps#279]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [x] The issue is reproducible on clean (=wiped /data/ partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

The checksum file `open_gapps-arm-5.1-super-20160313.zip.md5` wasn't generated.
Please see the screenshot of page [arm releases](https://github.com/opengapps/arm/releases/tag/20160313) below:
![img](https://i.gyazo.com/b522106c8f3d983ca10cc902764e7d3b.png)

**Reproduction Steps:**

N/A

**Expected behavior:**

N/A

**Observed behavior:**

N/A

**Installation debug log and logcat of FC:**

N/A

**Comment by mfonville** [comment]
@CheyiLin thanks for your report.
I did check the release on GitHub, and even though my buildbot has successfully generated the md5sum and has uploaded it to GitHub, GitHub releases did mark the upload process as erroneous and marked the file as broken and hides it to the public. (which is really weird for such a small file of only a few bytes, that it can fail).

In general, based on some feedback we received this week, it seems that the AWS-cloud that GitHub releases uses seems to have some problems. Let's hope the situation improves and the errors disappear, otherwise I will look into coding some extra checks+fallbacks in the buildbot.

**Comment by CheyiLin** [comment]
Got it. Thanks for your explanation.
:bow:

**Comment by mfonville** [comment]
@CheyiLin no problem, and if the problem is persistent don't hesitate to write here.
