### ISSUE TITLE
Removal of stock apps does not work accross multiple installs

### ISSUE THREAD

**Issue by F-i-f** [opengapps/opengapps#280]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**
- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope _(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))_

_If Open GApps compilation fails:_
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

_If Open GApps installation fails:_
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? _(other recoveries are only best-effort)_

_If receiving force closures after Open GApps installation:_
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself _(verify by e.g. installing the application from the Play Store instead)_
- [ ] The issue is reproducible on clean (=wiped /data/ partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
When using the "Remove apps" feature of opengapps, Opengapps will lose track of of the removed apps after multiple ugprade cycles.

**Reproduction Steps:**
1. Start from a clean install (wipe system first to get rid of addon.d scripts).
2. Flash a ROM (omniROM for me)
3. Install opengapps with a gapps-config.txt of:
   <pre>
   (Apollo)
   </pre>
   I include Apollo here, but the problem shows up with any app.
   At this point opengapps effectively removes the /system/app/Apollo directory and puts the code to remove Apollo in addon.d/70-gapps.sh.
4. Reinstall opengapps with the same gapps config.
   At this point, opengapps does not find the /system/app/Apollo directory and does not put the code to remove Apollo in addon.d/70-gapps.sh.  But Apollo is removed.
5. Flash the same ROM.
   Apollo is installed, and the addon.d script does not remove it anymore, and the app stays.

**Expected behavior:**

I would expect Apollo to be removed whatever the sequence of gapp/rom flashing is used.

**Observed behavior:**

When using the above flashing sequence (ROM, gapps, gapps, ROM), the apps I instructed openGapps to remove are back.

**Comment by mfonville** [comment]
I understand the issue. Normally the `()` instructions are only executed if only(!) a single instance of the folder was found, in either /system/app/ or in /system/priv-app/. It then stores the path to it and adds it to the removal-instructions of addon.d.
Of course the problem is, is that if you reflash-gapps on an install where the folder was already removed, it does not find this single occurrence, decides that it cannot find the app, and it does not add the removal-instructions to addon.d.

Best fix would probably be to lower the "only find it once" requirement into a "do not find it more than once" that clears both /system/app/ and /system/priv-app/ paths + adding in to addon.d by default.

I currently am working on fixing some other issues and this is quite a low priority. Always willing to accept PRs though if you find the time ;-)

**Comment by osm0sis** [comment]
I think this is resolved now by one of my commits awhile back. :+1:
