### ISSUE TITLE
Smart pre-ODEXing doesn't work correctly

### ISSUE THREAD

**Issue by USBhost** [opengapps/opengapps#288]
Nexus 9
ARM64 pico stock
Dirty Unicorns 6.0.1

http://pastebin.com/FjXAGNeU pico logcat
http://pastebin.com/M16fm3dV stock logcat
https://drive.google.com/file/d/0B1cOHQ70J9vlYmY2Y0N5YXl2M3M/view?usp=sharing install log pico

and it does not look like a permission issue
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.setupwizard.SetupWizardApplication" on path: DexPathList[[zip file "/system/priv-app/SetupWizard/SetupWizard.apk"],nativeLibraryDirectories=[/system/priv-app/SetupWizard/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by krutoileshii** [comment]
Same issue on cm13

**Comment by mfonville** [comment]
For some reason the smart pre-ODEX isn't seen by the ROM. Can you attach the install debug log?

**Comment by USBhost** [comment]
@mfonville  will do man tonight

**Comment by USBhost** [comment]
@mfonville here you go! http://pastebin.com/eSfwKUXP

**Comment by hurmaqny** [comment]
I'm having the same issue on Nexus 7 2013 (flo) with the latest snapshot (ZNH0EAO1QB) for CM13. I've installed arm 6.0 pico and I'm getting setup wizard fc.

**Comment by mfonville** [comment]
@USBhost I need the full debug log. It is a tar.gz file.

**Comment by USBhost** [comment]
@mfonville Its it

**Comment by mfonville** [comment]
@USBhost I probably did not have enough coffee yet... I did commit this: https://github.com/opengapps/opengapps/commit/b4b0c1c9ea3ba5445ae744f34b8f0c450f61829d
It reverts the pre-odexing as workaround until we sort this out.

**Comment by USBhost** [comment]
@mfonville why do we need pre-odexing?

**Comment by mfonville** [comment]
@USBhost the pre-odexing is to solve the issues that de-odexed APKs don't have a signature for classes.dex, because in the original it was absent. Some Marshmallow ROMs do difficult about this (and refuse to use the APK) so we try to pre-odex the classes.dex 'out of the APK' again so that it would pass verification.

**Comment by ALTracer** [comment]
So I got an arm64 device, installed some of your Gapps and a whopping 700MB of classes.dex appeared in /data/dalvik-cache. Whereas system apks have that right on the system partition, and user apps put that in /data/app.
Absence of preODEX kinda defeats the option to flash Gapps onto system partition's free space in order to clean the /data partition. GMS and Maps alone each occupy ~120MB. I don't think I can move the files manually properly, having had a bad experience, and TitaniumBackup would not help either.
Please have your time on the issue.

**Comment by osm0sis** [comment]
Smart Pre-ODEXing has been removed entirely.
