### ISSUE TITLE
Google Play services FC

### ISSUE THREAD

**Issue by USBhost** [opengapps/opengapps#310]
it looks like https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a is no longer sufficient for android-6.0.1_r43

to fix all the fc i just granted google play services all the available permissions

The logcat of the boot up are in https://drive.google.com/open?id=0B1cOHQ70J9vleXVUNUdVc1BvZkE flounder folder 

"AndroidRuntime: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission." this may be it?

Note: we may also need to grant permission to contacts
because before i granted the permissions google play services did not know i was loged in

**Comment by polyzen** [comment]
What happened to the issue template?

**Comment by mikalackis** [comment]
I recompiled my aosp for android-6.0.1_r41 (Nexus 5) and I dont have any FCs regarding permissions and I use the same patch as before.

**Comment by USBhost** [comment]
I did say android-6.0.1_r43 not r41

I wonder is arm64 any different?

**Comment by mfonville** [comment]
I believe the patch should result in granting the ACCESS_FINE_LOCATION permission. Are you sure this was a clean flash?
Maybe @TheCrazyLex could have a look?

**Comment by TheCrazyLex** [comment]
@mfonville It may be that some of the google apps require more permissions now. 

For confirmation someone would need to install the newest stock google image on a nexus device and then check which permissions are granted to every app. 

Unfortunately I don't own a nexus device. 

If someone can give me updated information, I will update the patch. 


Alex

**Comment by mfonville** [comment]
@NicholasBuse could you check this on your 6P?

**Comment by ralerbon** [comment]
**Sorry for my Bad English!**

I have the same issue with my HTC M9 (ARM64) 

I'm not able to grand the App (Play Service) all Permission, because the problem appears straight after starting a clean flash (Formatting the internal Storage+Wiping Data And Cache with TWRP) 

So the Setup-Wizard don't let me further then selecting an WLAN Access-Point, because he jumps back with the message that the "Play Service" closed.

I hope you enjoy'd my awesome English! ;)

PS: I use CandySix 2.1 (If this information helps)

**Comment by USBhost** [comment]
@mfonville 
it was on an clean install.
And I have a Nexus :)

I will flash the factory image tonight

**Comment by USBhost** [comment]
"Google Play services" has all available permissions granted on N

**Comment by vladimiroltean** [comment]
I'm also interested in an answer to this issue.

**Comment by USBhost** [comment]
https://drive.google.com/open?id=0B1cOHQ70J9vlR0t4cTh0Nmo4eTg

**Comment by vladimiroltean** [comment]
I am experimenting with a build for x86_64, and thus can only test Android M, not N for the moment.
Build is Android-x86, and tag is the same android-6.0.1_r43:
```
commit 26a000e7bc87b3f428cbb57a53e22f154a5fe573
Merge: 52bb844 4eac1d4
Author: Chih-Wei Huang <cwhuang@linux.org.tw>
Date:   Fri May 6 03:33:04 2016 +0800

    Merge remote-tracking branch 'aosp/android-6.0.1_r43' into marshmallow-x86

```

I am providing my [full logcat](https://drive.google.com/file/d/0BycBHkd7fD4AdHpaWHNzSkE4T2s/view?usp=sharing) output.

**Comment by jawz101** [comment]
I wish you all would hold off on the update for any variant of Google Play Services 9.0.83.  I have both a Google Nexus 5 on CM13, Chroma, Purity and Samsung Galaxy Tab S on CM12.1 and Google Play Services starts force closing as well as any other app which uses Google Play Services (gmail, Music, etc.)  There's an issue with this latest version and, as you can see, it's affecting several devices as well as AOSP and CyanogenMod on both Lollipop and Marshmallow code.  Bottom line- it's the app not the ROM or device.

**Comment by TheCrazyLex** [comment]
@USBHost I think it is currently all about Marshmallow. So such a picture on the newest stock M release would be more helpful. 

Thanks!

**Comment by vladimiroltean** [comment]
My Google Play Services version is 8.7.03 (2645110-480).

**Comment by polyzen** [comment]
No force closes with 9.0.83 here. [CopperheadOS](https://copperhead.co/android) May 8th release (Android 6.0.1 MOB30J).

**Comment by USBhost** [comment]
@TheCrazyLex ... I almost guarantee it will literally be the same but as you wish
I will give it to you by tonight.

**Comment by jawz101** [comment]
My bad, folks.  Ignore my comment.  For the past week I've experienced fc's with the latest Google Play.  This morning I found a Reddit thread that said if you use Amplify XPosed module and had it active for the icing wakelock the latest Google Play Svcs doesn't like that.  I just uninstalled Amplify for now and the problem immediately went away.

**Comment by USBhost** [comment]
@TheCrazyLex
Well... here you go
https://drive.google.com/open?id=0B1cOHQ70J9vlODI0YXo0Mm1uM0k

**Comment by TheCrazyLex** [comment]
@USBhost Thanks for updating me.
I rechecked and my patch is already granting all the permissions on your screenshot to Google Play Services.

Alex

**Comment by USBhost** [comment]
@TheCrazyLex then why did it not grant permission to them on r43

**Comment by TheCrazyLex** [comment]
@USBHost are you sure the ROM you are using has the patch applied?

**Comment by USBhost** [comment]
Yes!
The only fc I got was Google Play services.

No setup wizard fc
No google play fc
Only Google Play services.

**Comment by Galaxy-Crusader** [comment]
Does anyone get system ui fc, it only starts after multi selecting apps to install.

**Comment by mfonville** [comment]
@Galaxy-Crusader your problem sounds like a ROM issue, probably best to drop them a line. For support you need to post your debug logs and logcat at our XDA thread.

**Comment by dlmetcalf** [comment]
@polyzen, Regarding CopperheadOS, when you say "They do not want/intend to support GApps",   that needs some clarification see this thread: https://twitter.com/CopperheadOS/status/740247728173678592

I'm not part of their team and cant speak for them - but I think it'd be clearer to say; they're unable to compromise security as required by the current OpenGApps install method.  I've seen the Copperhead team members give a lot of assistance to people, helping them get GApps running on devices - but they're also a very small team and first priority MUST be ensuring security features are covered first.  They don't have the resources to fix OpenGApps or provide user support for something that's outside their control.

The core issue (or at least the one I'm aware of), is the way OpenGApps handles permissions. It's been implemented very insecurely.  It would great if someone in the OpenGApps community can implement features like signature verification of OpenGApps APKs, before just granting permissions to any application that happens to share the same name - because that directly exposes the whole OS to spoofing.  Given that one of major reasons people use OpenGApps is to gain more control of their devices (e.g. for security reasons), it would be great to see it implemented.

https://github.com/opengapps/opengapps/issues/93#issuecomment-154181847

Note, in general, Copperhead team don't advocate for installing GApps, because it hands device control to Google. That doesn't align well with the security objectives of the CopperheadOS project.  That said, they're still open to allowing OpenGApps if users want to go down that path themselves - but they're only going to consider safe modifications to allow it (not hacks), which they don't intend to develop themselves, and they won't be offering a support service for it either.  (At least I'm fairly sure that's their position based on what conversation I've observed).

I haven't looked closely at OpenGApps to know the full scope of what's required, but if it's of use, I know there's at least examples of signature verification code in FDroid (e.g. https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/RepoUpdater.java).  Implementing that verification would be a good start if someone has a chance.

**Comment by shkschneider** [comment]
@TheCrazyLex Talked on Gitter with @mfonville about a Force Close I have that happens on this month build (`android-6.0.1_r60` Nexus 5) of my ROM (make clobber, make dist, wipe all, flash) with OpenGApps ARM July 2nd, Pico.

```
FATAL EXCEPTION: GoogleLocationService
Process: com.google.android.gms.persistent
java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
```

The TeamExodus patch (https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a) includes `LOCATION_PERMISSIONS` for `com.google.android.gms`.
I even added `LOCATION_PERMISSIONS` to `com.google.android.gms.persistent` without any change. Google Play Services Force Close upon the first fresh boot during the Setup Wizard and after...

In my settings, nothing is checked (the opposite of https://drive.google.com/file/d/0B1cOHQ70J9vlR0t4cTh0Nmo4eTg/view). As soon as I (manually of via `adb`) allow the 'Location' permission, the Force Close is gone.

Is `com.google.android.gms.persistent` same as `com.google.android.gms`?
How does my problem happen and how to fix it? I'm out of ideas since I included the patch...

**Comment by USBhost** [comment]
Just reopen if the problem comes back.

**Comment by TheDoubleB** [comment]
I'm getting this exact issue. My setup is: LineageOS 14.1, Android 7.1.1 (built by me) with OpenGApps nano built into the image itself. Google Play services version is 10.2.98.

Since you were all talking about Android 6.x, is it possible that this is the problem of the newer Android 7.x?

**Comment by shkschneider** [comment]
I still have the exact same problems as https://github.com/opengapps/opengapps/issues/310#issuecomment-237255546
