### ISSUE TITLE
Gapps for mips/mips64

### ISSUE THREAD

**Issue by Displax** [opengapps/opengapps#317]
I was able to grub some mips apk`s, like GMS (050), Play Games (050) and Youtube.
Already uploaded it on https://www.apkmirror.com/

If you need some other apk`s please tell me exactly which and I try grub it.

Thanks.

**Comment by mfonville** [comment]
@Displax we had indeed noticed your uploads on apkmirror, especially because you also have x86_64 apks :)
We probably won't do Open GApps for MIPS, because as far as we know no new MIPS devices have been made since the 4.x Android series.
If MIPS would become 'mainstream' again we could also do minimal packages for it.

Can I ask you what tool(s) you use to get your APKs?

**Comment by Displax** [comment]
@mfonville 
On android <5.0 you can modify build.prop for needed ABI, density and probably API level (don't tried it yet) without any consequences, like bootloops. Then clear GMS and Google Play data and reboot device. After some time, Google Play starts download apps for fake values.

So, in this way you can grab all apk`s for each ABI, API and density.
If it`s works on emulators, you can try to create emulators for all combination.
Or, perhaps, you can find a better way to automate this thing.

Glad to help. :)

**Comment by mfonville** [comment]
@Displax I use our apkcrawler tool https://github.com/opengapps/apkcrawler with various GSF IDs for the playstorecrawler. But I need to improve the current Google proto's that we use, to mimic those of Google Login Services Framework.

I will close this bugreport, but if you find this interesting, please take a look at the apkcrawler project. We would really welcome some extra help that essential part of the GApps endeavor :)
