### ISSUE TITLE
Provide documentation a range of how much diskspace each package needs

### ISSUE THREAD

**Issue by MrStonedOne** [opengapps/opengapps#323]
This prevents the user from even knowing what smaller package to download because they have no clue what order of magnitude they are off the mark.

On this note, http://opengapps.org/ should tell the user the required system free space to install for each package set, or at least a range if this can't be exactified.

**Comment by mfonville** [comment]
The total system space and free space are already shown in the log explicitly in the summary.
The details are shown per app in the calculation.
Exacts are not possible to predict, because they depend on device-specific factors like DPI. Ranges are currently not specified/available (and I lack the resources to do so). If somebody has the time to aggregate this data they could e.g. be added to the wiki.

In the near future (when Google releases its new devices) we will probably re-evaluate the packages' content and part of that assessment will be the required diskspace. At that point we could indicate that diskspace requirement range.

**Comment by NatoBoram** [comment]
Speaking of disk space, a package that only replaces existing system apps (meaning a minimal space requirement) would be awesome.
