### ISSUE TITLE
Add peer5 download mirror

### ISSUE THREAD

**Issue by ruifung** [opengapps/opengapps#340]
Is it possible to do that? As at times (read: pretty often) the download from github (which apparently is using amazon AWS) is pretty slow (<30kB/s).

**Comment by mfonville** [comment]
@ruifung hi, AWS is sometimes slow but GitHub support is aware of the issue and looking into it. We are also looking into peer-2-peer accelerators ourselves, but have no solution yet that we can host because we lack capacity on the buildbot.

Peer5 is no solution for us, after their free trial their prices are higher than we can afford (there is a lot of traffic and a lot of adblocking). So they are no option.

**Comment by ruifung** [comment]
@mfonville I would hope so, because for the past few days, my download speed for this has been horribly slow. And when you're trying to download the Aroma package... lets just say 3 kB/s is not exactly helping...

**Comment by mfonville** [comment]
@ruifung we don't allow any mirrors (see our blog article about the policy http://opengapps.org/blog/post/2016/03/18/the-no-mirror-policy/ )
You can try to use a download manager if you have issues.
GitHub is trying to improve the situation, but you can always drop them a line if performance is *that* bad, because though slow for some locations might be an inconvenience, such speeds make in effect their service unusable at all.

**Comment by Majal** [comment]
I'm using this workaround instead... Helps in the moment. :-) Feel free to edit the code to fit your needs.

https://github.com/Majal/maj-scripts/blob/master/ogapps
