### ISSUE TITLE
Contacts synced by Pico version

### ISSUE THREAD

**Issue by Exaeta** [opengapps/opengapps#344]
The gapps pico version syncs contacts with your google account. This is not desired. Please remove the contacts sync.

**Comment by USBhost** [comment]
Isn't that a core feature?

**Comment by mfonville** [comment]
This has been discussed before and doesn't make any sense, hence will not be removed from the core apps, see https://github.com/opengapps/opengapps/issues/155

**Comment by Exaeta** [comment]
No it's not a core feature. Please remove it. The ability to create local contacts is LOST when this is enabled.

**Comment by mfonville** [comment]
@Exaeta since ICS already AOSP/Google decided that any contact in Android should be associated with an account. That is why 'local contacts' is only shown if no account (not only Google, also Exchange etc) is set-up a local contact is created. All vendors in OHA are obligated to bundle a (preferably Google's) contact sync.

As such *"The ability to create local contacts"* in AOSP contacts app is not meant as a feature in Android, but a last resort fallback. Ofc alternative contact software (so not the AOSP or Google one) can still allow you to create local contacts.
Your contacts are send to Google anyhow regardless of this, because big brother Google Play Services hooks up to every data on your system it can gets it hands on.

Ofc you can always spin your own build of a package excluding contactsync, you need to remove just 1 line and compile.

**Comment by Exaeta** [comment]
I understand what you're saying, but it's false for a simple reason.

First, Google is a US company. And second, it would be illegal under US law for Google to upload local contact information without permission. (no Google's TOS wont count in this circumstance.)

Google disables the ability to make local contacts to ensure it can legally upload all your contacts. But if it turns out Google is uploading local contacts, then Google can see me in court. In order to prevent Google doing this, I need to make my contacts local.

**Comment by mfonville** [comment]
You can try to take them to court. But if you look at https://myactivity.google.com/myactivity and what they are tracking, they log literally everything. Though I am sure as long as your address information is not further processed/shared by them, they are acting within the current privacy shield agreement. (unlike evil companies like sync.me who publicize such private information about, but even about them the Dutch authorities said they saw no legal possibility/reason to act).

If you are unhappy about the situation, this is the wrong place to resolve it, you can complain to Google at e.g. this issue:
https://code.google.com/p/android/issues/detail?id=26834
Or use another contact app, e.g. one from https://f-droid.org/
Or, as I said in previous comment, you can still create your own build without contactssync, but I am sure your contacts are sent to them anyway via GMS.
