### ISSUE TITLE
Google Maps library v1 missing or broken in gapps (stock, August 24, 2016)

### ISSUE THREAD

**Issue by sndirsch** [opengapps/opengapps#350]
The app "Öffi" - a very popular Journey planner for pulic transportation in Germany - is not working on my OnePlus 3 with CM 13 (Release from August 20 2016) and open gapps ARM64 Stock variant from August 24 2016. The author told me that very likely the Google Maps library v1 is missing in the ROM or not working properliy. Meanwhile I figured out that 

  /system/framework/com.google.android.maps.jar 

exists (I believe this is this library), but apparently it doesn't work properly. I'm not aware of any other application not working with CM13 and gapps I'm using.

**Comment by mfonville** [comment]
This is already fixed in since August 30th builds: https://github.com/opengapps/all/commit/f93cde0f1d90fcdf680f02dfd0d9e0e19c906194
Please try one of the more recent packages.

Please also take not that the best place to report such an issue is on the XDA Forum (where this also has been discussed in the thread)

**Comment by rapperskull** [comment]
Have you tried using the latest OpenGApps build?

Il 06 set 2016 3:18 PM, "Stefan Dirsch" <notifications@github.com> ha
scritto:

**Comment by sndirsch** [comment]
Thanks for the quick response! The update to the version of Sep 6 fixed the issue.
