### ISSUE TITLE
OpenGapps install overwrites the system startup wizard on MIUI ROM

### ISSUE THREAD

**Issue by WIP42** [opengapps/opengapps#363]
When flashing OpenGapps on a MIUI system that has been factory reset, 
- the Google SetupWIzard package replaces the system's Setup Wizzard
- Once device is started, the new Wizzard cannot continue - it is stuck at the choose languages screen (Chinese & English the only 2 options)

I have attempted to edit the install.sh script to skip deletion of stock Wizard and to _NOT_ install the Google one with no luck.

Best Regards
P

**Comment by mfonville** [comment]
Could you get a logcat of why the wizard is not able to continue? I would have to know what is going wrong.
Also please attach your install debug log (the tar.gz file)

**Comment by WIP42** [comment]
Hi @mfonville / Maarten; I will do so tonight after a backup:-) didnt see any errors in the install debug log; I did however choose only certain packages - hope I still have the config backed up someplace

**Comment by tenninjas** [comment]
I'm unable to get the log from the device since there is no way to save it and no way to complete the wizard, but I can tell you the error is from MIUI's setup wizard saying it requires a MIUI theme to continue; so it is not necessarily that the wizard itself is broken but rather that it can't find the theme files.

**Comment by mfonville** [comment]
so, after Google's setupwizard, it starts the MIUI wizard, but the MIUI wizard fails?

**Comment by tenninjas** [comment]
In my experience it did not start the Google setupwizard at all. It started the MIUI wizard but failed before loading the Wifi connection screen. If I choose to 'report', I can see that the error is from the MIUI wizard and is because the theme is not a MIUI theme.

**Comment by mfonville** [comment]
Could you then at least upload the Debug Logs? Because what would help is probably removing the MIUI SetupWizard all together (but I'd need the filepaths for that)

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by pras92** [comment]
Can we re-open this issue? 
To update: Facing this rarely spoken issue, after about 6 years of OP, is weird and unlucky! 
Device: Olivewood
ROM: Stock MIUI (12.5.6.0.QCQINXM)

Doing a Clean flash ROM + Open GApps overwrites the default (MIUI) startup wizard. Never seen [IMG #1](https://user-images.githubusercontent.com/24977679/171994878-bd770106-2956-4cd4-bf4d-6b776f17dc0d.jpg) before, shows up only when clean flashing Open GApps.

Startup wizard doesn't go further (see [IMG #2](https://user-images.githubusercontent.com/24977679/171994889-bb6d805d-8024-445c-933f-1a018b1c3386.jpg) and [IMG #3](https://user-images.githubusercontent.com/24977679/171994886-f00406a1-492d-430b-ac56-be7d8a341d01.jpg)), after the Google Location services step, thus making the device unusable with Open GApps flashed. I doubt if it's even actually installed, as said in the XDA post, check below. 
 
While the attached debug logs are from PBRP, the results were exactly the same with TWRP. I understand Open GApps officially supports only TWRP, but a point to note is, PBRP is just a port of TWRP for some devices without native TWRP support. 
 
[[clean] open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/8837465/clean.open_gapps_debug_logs.tar.gz)

Additionally, tried dirty flashing after debloating Google and Xiaomi bloatware. Reported to [XDA thread here](https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/post-86981925), since it involves pre-built Open GApps package. It resulted in successful flash but no Play Store & Play Services being installed.

**Comment by osm0sis** [comment]
I'd rather you open a new one.
