### ISSUE TITLE
Aroma + hammerhead + twrp

### ISSUE THREAD

**Issue by szhu** [opengapps/opengapps#386]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

This combination works:
- hammerhead-m4b30x-factory-10cfaa5c.zip
- twrp-**3.0.1**-0-hammerhead.img
- cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J2-hammerhead.zip
- open_gapps-arm-6.0-aroma-20161118.zip

This combination doesn't work:
- hammerhead-m4b30x-factory-10cfaa5c.zip
- twrp-**3.0.2**-0-hammerhead.img
- cm-13.0-20160820-SNAPSHOT-ZNH5YAO0J2-hammerhead.zip
- open_gapps-arm-6.0-aroma-20161118.zip

Under the latter combination, the log line "Performing space calculations" is the last thing I see, then TWRP restarts.

**Comment by mfonville** [comment]
Aroma-Installer has known problems that we cannot resolve, because the maintainer of the Aroma-Installer that we use for the aroma projects does not work on his project anymore. (more info in the XDA thread of the aroma package: http://forum.xda-developers.com/android/general/gapps-lp-gapps-pa-gapps-aroma-installer-t3010798 )
Try to use one of the other packages in combination with a `.gapps-config` file
