### ISSUE TITLE
Apps are integrated but not deleted after update

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#41]
I had this issue both on a install of fornexus on a dirty flash (formatted system but not data and installed) and a completely fresh install of CyanogenMod with stock package.

After apps are updated though Google Play, they remain in data even after installing a new GApps package. They do get updated in system, but it's still in data as the same file.

This picture shows what apps are still in data as of July 3rd's build: https://goo.gl/photos/xhvbb7Lh7HxswEFf7

Logs and packages.xml are here: https://goo.gl/l2y2HP

**Comment by bgiesing** [comment]
@rapperskull Still happening to me after installing a new ROM fresh and flashing another package on it and using Stock instead of fornexus.

**Comment by mfonville** [comment]
This is something that Android itself has to fix, it is responsible for cleaning out /data/ when /system/ has newer packages. I did read somewhere that in recent CM builds it was probably broken when packages are 'equal' instead of newer, but we ourselves cannot do anything about it.

**Comment by bgiesing** [comment]
Any possibility of re-looking into this? Somebody on TK's GApps thread mentioned the reason why:
```java
/// PackageManagerService.java:
/// lollipop-mr1-release
lines 4302: if (pkg.mVersionCode <= ps.versionCode) {

/// kitkat-mr2.2-release
line 3605: if (pkg.mVersionCode < ps.versionCode) {﻿
```

It looks like a one-character change on the ROM end would fix it (the = sign being removed)... However, AOSPA and CyanogenMod have already said they won't implement it as it is by design and said to look into having the GApps do something.

**Comment by mfonville** [comment]
I did read this too. But we can't do anything, the ROM developers have to fix this (line of code)

**Comment by mfonville** [comment]
Since it is relatively unsafe to mess with /data/ of users from TWRP, it might be worth to find a solution for this from a different perspective.
Somebody might want to write a 'normal' Android App that compares the version of an app that is available on /system/ and the version that is provided on /data/ by using e.g. the PackageInstaller and PackageManager classes. That app could then automate the deinstallation of the non-necessary updates on /data/ via the regular Android app management mechansims.
Such an app could be used for all GApps packages.
