### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by KryptoknightDB** [opengapps/opengapps#470]
Hello! Open Gapps Team

I am having issues in downloading the needed file i have used idm, chrome, uc browser, mozzilla firefox
but got no lock it says the link is expired and this happens after 30% is complete
so if you can give me a torrent file for arm 4.4 stock so it would be a great help.

I really need this as i installed a custom rom and didn't backup the stock so i found a deodexed stock rom for my device but it had no gapps. Even it dont have google play sevices working properly i get this message:Google Play Services Has Stopped Working. 

So i think you'll fix my problem asap

Thanks

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by KryptoknightDB** [comment]
Sorry for that
You didn't even read my issue its not about installing or any other error not expected this answer. 
And how can i give you logcat or debug file if its not just downloading
I downloaded it 12 times using different methods but got no luck i'll find another way than requesting you.

**Comment by mfonville** [comment]
Instructions how to handle the situation are on http://opengapps.org/#support (the 'support' tab of the webpage).

Use a download manager and feed it the github-url for the download; it will support resume.

**Comment by KryptoknightDB** [comment]
still not working

**Comment by KryptoknightDB** [comment]
can't understand why you can't provide a torrent

**Comment by sankalp15** [comment]
from where to get GitHub url
I am downloading using DAP during downloading it asks for authentication.

**Comment by mfonville** [comment]
On opengapps.org select the architecture and click on the 'older releases'. Those are the links you need.
Torrents can't be supplied, because the buildbot has limited upload capacity, and the assets are outdated after one day. I also looked at http+torrent combination providers, but they charge really a lot of money that we can't afford.

Best is also to let GitHub (that hosts the downloads) know that you experience these connectivity issues during download.

**Comment by ndbroadbent** [comment]
Hi @mfonville, I just wanted to mention that I just spent many hours trying to download a 691MB stock file (and maybe 10 attempts), but it kept stopping, and my download manager couldn't resume the download. The tip to download the file directly from https://github.com/opengapps/x86/releases/ was super helpful, so thanks for that! My download manager is now properly resuming paused downloads.

I really think that should be the default link, at least for larger downloads. At the very least, it would be great to show a warning when you select one of these huge files, because that was a really painful experience.

Just my 2c, and thanks for all your work!

**Comment by imkon** [comment]
I've tried more than 10 times to download arm 6.0 pico gapps, but every time it fails mid way.I've both ways - downloading from opengapps as well as from GitHub.Tried on every browser.Not one method works.Please help.

**Comment by jessicandavis** [comment]
I hate to be a pain like OP, but I can't dl 14.1. Have tried several packages, nothing is working. Not sure what's up. 

And **thank you** for your hard work :)

**Comment by jessicandavis** [comment]
Just FYI everyone: used a download manager as per the wiki here (after three failed attempts), and it finally worked. Might be the only way to go right now.

**Comment by adriespo** [comment]
Sorry to bore you but what download manager? With uget I get a 403 error.

**Comment by MacGWik** [comment]
Everytime I use the github.com/opengapps/ link, I always redirected to S3 amazon link.
How can I download it direct from github.com/opengapps/ ?

**Comment by valterh4ck3r** [comment]
Same problem.

**Comment by tanvijoshi02** [comment]
Same issue
Can someone please help me to solve this
