### ISSUE TITLE
How to build GApps with only few language ?

### ISSUE THREAD

**Issue by YandexStudio** [opengapps/opengapps#479]
My device is Galaxy Nexus and the /system is only about 700MB so i need all packages in system partition to be as small as possiable. How to build GApps that only include English & Chinese ?

**Comment by chinmaykunkikar** [comment]
@YandexStudio Can you elaborate "all packages"? You mean apps in system partition?
If yes, then editing/deleting strings from an app is **not possible** since all gapps are close sourced. Also, it won't have as much big of an impact on the app size.

P.S. If you mean something else instead of this then pardon me, and help me understand :smile:
