### ISSUE TITLE
Latest Aroma GApps Package combined with TWRP 3.x

### ISSUE THREAD

**Issue by pr030880** [opengapps/opengapps#493]
First of all, I know there seem to be problems with my device, Galaxy S5 (ktle) and others as well :-(
 - Known broken TWRP versions: 3.0.2-2 (Crashes TWRP), 2.8.4.0 (Doesn't install everything you select)

TWRP 2.8.4.0 works for at least for me. The only workaround for me is:

I've tried to flash the GApps-Aroma package several times with TWRP 3.1.0-1. Everytime GApps Aroma launches, TWRP hangs/freezes. The only way to get out of TWRP is remove the device's battery and re-enter TWRP. The only current workaround for me is:

- Flash TWRP 3.1.0-1
- Flash LineageOS with TWRP 3.1.0-1 (TWRP 2.8.4.0 does not work for LineageOS 7.1.2)
- Flash TWRP back to old release 2.8.4.0
- Flash Aroma GApps (most of the times it works with 2.8.4.0, not always - but at least TWRP doesn't hard freezes, it just reboots)
- Flash TWRP back to latest 3.1.0-1 after GApps has been flashed with 2.8.4.0

**The Team Win's response to this was:**
Unfortunately AROMA is deprecated, as the source hasn't been updated to be compatible with newer versions of Android, while the TWRP source is constantly being updated. It seems that unless AROMA source is updated soon, it will eventually be completely incompatible with newer versions of TWRP. Unfortunately there's not much we can do about that.

https://github.com/TeamWin/Team-Win-Recovery-Project/issues/943

According to that response the problem is the Aroma package, which I personally prefer, because it is very handy in customizing what to install and what not. Is there a way, that you guys can solve this problem?

**Comment by raulpetru** [comment]
I'm sorry to say, but we can't actually solve this problem.

There are only workarounds for now. For example one workaround is by modifying TWRP to make it compatible with AROMA. I don't really know the exact changes that are needed to be made in order to make AROMA compatible with TWRP.
On my device, OnePlus X, AROMA never worked in any available TWRP version but recently somebody came up with an unofficial TWRP version that supports AROMA. If you are interested about this maybe you can ask the creator. Here's the [thread](https://forum.xda-developers.com/oneplus-x/orig-development/recovery-twrp-r1-03-05-t3600887).

Hopefully [amarullz](https://forum.xda-developers.com/member.php?u=402300) will update AROMA someday. Or maybe somebody will fork the project and update it, who knows?

An alternative to AROMA could be an gapps-config generator (see _[Advanced Features and Options](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options)_). We thought about making this gapps-config generator on our website but I don't have the time to work on this at the moment.
