### ISSUE TITLE
QUESTION: Is there an explanation of /system/etc/default-permissions/?

### ISSUE THREAD

**Issue by ale5000-git** [opengapps/opengapps#518]
Hi,
is there an explanation of /system/etc/default-permissions/?

I would like to know if possible how it exactly work and when it is used by the ROM.

**Comment by jawz101** [comment]
I assume it's what permissions get granted when you click the reset permissions button.

**Comment by ale5000-git** [comment]
Thanks for the reply but I meant a technical explanation of the format and of what can be used.
I want to know exactly instead of guessing it from existing files.

**Comment by mikalackis** [comment]
This is the list of permissions that are granted by the system to various apps when the ROM boots up so that they can work out of the box. Thats how google apps work as soon as you turn on your phone. 

There is a comment explaining this here: https://android.googlesource.com/device/google/marlin/+/nougat-dr1-release/default-permissions.xml

Also, check this out, this is changed a bit in 8.0: 
https://source.android.com/devices/tech/config/perms-whitelist

**Comment by ale5000-git** [comment]
Thanks for the reply but I have some doubts:
- Does the xml need to list only permissions that are asked at runtime or all of them?
- Also if in the xml it contain a permission not supported by the ROM does it only ignore it or it can cause problems?
