### ISSUE TITLE
QUESTION: Installing Open GApps to another partition for devices with limited /system/?

### ISSUE THREAD

**Issue by Gulpy** [opengapps/opengapps#550]
Hi guys,

Sorry if this has already been answered or the technical reason why is obvious, however I have searched around and cannot find an answer for this or an option in the advanced configuration.

I have a Nexus 5 with LineageOS and would like to use the stock package which is too large for the system partition, I understand that the general recommendation in this situation is to use the nano package and then install other apps manually, however removing all of the preinstalled alternatives and then installing so many extra packages manually is very difficult and especially annoying with updates, which LineageOS has weekly.

Is there any way to configure the script such that it removes all of the preinstalled alternative apps from my /system/ partition and then installs all apps from the stock package in my data partition? This would be very helpful if possible.

Kind regards,
Charlie

**Comment by YandexStudio** [comment]
Although I'm also a user but I can tell you it's impossible.
You mean you want just install all the Gapps which can replace the stock, such as dailer, messenger, etc.
Because Gapps use Google Play Service, it's much larger than AOSP builds, for example, the stock calculator is less than 0.5MB but Google Calculator is about 1MB . This means even just use Google one to replace ALSO one, it still needs more spaces.
On some device like your Nexus 5, it will be okay to replace all the AOSP apps with Google's , but on some other devices, for example, my Galaxy Nexus, the /system partition is even smaller,  then I have to choose whcih apps still use the AOSP one, as Android 6.0 cannot use Chrome as Webview provider, and there's no enough space to install both Webview and Chrome, I finally choosed keep the stock browser.
The script cannot know what you want if it have no enough space for replying all stock apps. So just use the aroma package, it will be fine.

**Comment by Gulpy** [comment]
@YandexStudio I am not sure if you read my question, I know that I want to use the Open GApps "stock" package to replace the AOSP and other alternative apps that come with my ROM (LineageOS), however the system partition on a Nexus 5 is too small for this, so I want to know if there is any way to have the script remove all of the alternative pre-installed apps from the system partition and then install the new apps to the data partition as the Play Store would, as the data partition is large enough to accommodate all of these apps.

**Comment by YandexStudio** [comment]
I mean even replacing all the aosp to gapps is not possible for every device, installing the remain gapps to data partition is impossible too. If not all the aosp apps are replaced by gapps, how could the script know which it REMAINS ?

**Comment by Shished** [comment]
You should checkout [this](https://forum.xda-developers.com/apps/magisk/module-systemless-beansgapps-mini-7-1-x-t3611362) magisk module.
It installs opengapps zips systemless-ly (all files are stored in /data/magisk.img file).

**Comment by Gulpy** [comment]
@Shished this is great, thank you so much!
