### ISSUE TITLE
QUESTION: Apk with lib

### ISSUE THREAD

**Issue by tillaz87** [opengapps/opengapps#557]
Hey, 

I'm just wondering how you repack apk with lib for system install in the Gapps package? 

Some of the TV apps have been outdated a few week so I would like to be to take them from my device to update my rom, but the apk with lib seem to be compressed different and just fc

Any help would be great 

Thanks

**Comment by kevin686868** [comment]
Thanks

**Comment by kevin686868** [comment]
Great

**Comment by kevin686868** [comment]
yea

**Comment by kevin686868** [comment]
your great

**Comment by kevin686868** [comment]
good

**Comment by kevin686868** [comment]
love it

**Comment by kevin686868** [comment]
thanks

**Comment by kevin686868** [comment]
done

**Comment by kevin686868** [comment]
yeai

**Comment by tillaz87** [comment]
Been at that crack pipe again?

**Comment by kevin686868** [comment]
What's this message about

On Dec 8, 2017 12:07 PM, kevin196819681968@gmail.com wrote:



On Dec 6, 2017 10:18 PM, "tillaz87" <notifications@github.com> wrote:

Been at that crack pipe again?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/opengapps/opengapps/issues/557#issuecomment-349850613>,
or mute the thread

**Comment by tillaz87** [comment]
What's spamming this question about?

**Comment by kevin686868** [comment]
What are you talking about

**Comment by tillaz87** [comment]
All those posts you put on my question on github... Which have now been
deleted
