### ISSUE TITLE
[RFE][OREO] Install opengapps to /odm?

### ISSUE THREAD

**Issue by cryptomilk** [opengapps/opengapps#562]
Hi,

in customs ROMS if you enable verity for /system. You're not able to install opengapps. However most devices have a prebuilt or oem partition. This can be mounted to /odm and then it would be possible to install opengapps there. The system looks in /odm for apps, so would this be possible?

Check for /system verity, if this is turned on, check /odm and install there if possible ...

**Comment by cryptomilk** [comment]
Not really, the oem partition can be mounted to /odm. A lot of phone have preload partition which provide a bunch of addtional apps (like facebook etc.) those could be mounted to /odm.

**Comment by MSF-Jarvis** [comment]
Well you can mount virtually any partition to any mount point, that's not the point of this. What you're suggesting will have to wait for OEMs to release Oreo powered devices, because most opengapps Oreo users are custom ROM guys who don't necessarily have the said extra partition which has been mandated by Oreo VTS.
