### ISSUE TITLE
Tvstock (arm): AndroidMediaShell fails for some reason

### ISSUE THREAD

**Issue by gabrielgagz** [opengapps/opengapps#568]
In latest builds chromecast receiver stopped working:

`01-03 23:27:24.032  1253  1321 I ActivityManager: Waited long enough for: ServiceRecord{1234dec u0 com.google.android.apps.mediashell/.MediaShellCastReceiverService}`

When you trying to cast:

`01-03 23:30:40.330  2553  2773 E chromium: [2553:2773:ERROR:client_auth_signer.cc(295)] Cast certificate is not valid.
01-03 23:30:40.330  2553  2773 W chromium: [2553:2773:WARNING:client_auth_signer.cc(262)] No private key, hence empty signature.
01-03 23:30:41.049  2553  2553 E chromium: [2553:2553:ERROR:client_auth_signer.cc(295)] Cast certificate is not valid.
01-03 23:30:41.049  2553  2553 E chromium: [2553:2553:ERROR:client_auth_signer.cc(295)] Cast certificate is not valid.
01-03 23:30:41.050  2553  2553 E chromium: [2553:2553:ERROR:client_auth_signer.cc(295)] Cast certificate is not valid.`

My device (Forge TV) is L1 provisioned. https://github.com/gabrielgagz/android_device_razer_pearlyn

If i install olders versions, and i update the package via Google Play, package works with no problem.

**Comment by npjohnson** [comment]
If you're using Lineage, this isn't OpenGApps fault. Wait until next weeks builds and see if it still doesn't work. Take a look at fugu's recent changes for Lineage, there are a few required to make them compatible with Lineage's ATV vendor.

**Comment by gabrielgagz** [comment]
I'm using on my own unofficial build for pearlyn (Forge TV). Probably was related to outdated vendor blobs, it works now. I'm closing this, thanks.

PS. We are a few ATV developers, we should create a telegram group or something to share experiences

**Comment by anishsane** [comment]
Wait. How was this fixed?
I am facing this issue for the locally compiled (unofficial) build for porg device (android tv build for nvidia jetson nano device).

I followed these steps: https://wiki.lineageos.org/devices/porg/build/variant2

And yes, I am also seeing the error in the youtube app on my phone that says, "device couldn't be verified. This could be caused by outdated device firmware."
So, I am probably having the same issue as you faced.
