### ISSUE TITLE
Provide zsync files as part of build process so that bandwidth can be saved while downloading from remote source.

### ISSUE THREAD

**Issue by nmabhinandan** [opengapps/opengapps#574]

**Comment by ramaq** [comment]
رائع جدا و جميل

**Comment by jmichael2497** [comment]
like ubuntu distros do to update the 1GB iso with weekly 200M of differences, and can also be used to recycle the existing good portions and prep that iso to "fill in the blanks" (less efficiently) using bittorrent as well, then transfer from pc to mobile (or even run from mobile directly maybe).

_not sure of proper etiquette, so copying [my comment to LineagOS sub-reddit](https://www.reddit.com/r/LineageOS/comments/9w9vik/lineageos_151_oreo_is_moving_to_nightly_builds/e9nyygc/) below._

all this "delta updating" can be easily handled like various linux distros have been doing for years with zsync.

***if there is no initial file to update, or it is damaged, it does not matter at all to zsync, since it can just start a full download from the beginning, which is all LOS update already does every time.***

one easy big example is ubuntu using zsync (basically a smarter rsync) as part of their automated processes of daily builds for testing (but they also have a sort of fixes in by friday weekly cycle), so i just run zsync friday mornings and watch it re-use what it can out of my existing iso and usually only downloads around 200M out of 1000M to make a new complete iso.

zsync could be run directly from the device and is basically foolproof as well, since it looks inside the iso or specifically built zip and uses hashes of the files inside to check what is still being used in the new file.

zsync can also be set to make sure it matches exactly in the end, for signature validity, rather than just being the files collected and zipped.

technical papers existing since 2005 for linux

* [http://zsync.moria.org.uk/papers](http://zsync.moria.org.uk/papers)

port existing since 2012 for windows

* [https://app.assembla.com/spaces/zsync-windows/documents](https://app.assembla.com/spaces/zsync-windows/documents)

example use case in the wild

* [http://cdimage.ubuntu.com/lubuntu/bionic/daily-live/current/?C=S;O=A](http://cdimage.ubuntu.com/lubuntu/bionic/daily-live/current/?C=S;O=A)

instructions and example script

* [https://help.ubuntu.com/community/ZsyncCdImage](https://help.ubuntu.com/community/ZsyncCdImage)

hope that helps, as i know it saves me and everyone else a lot of time and bandwidth, along with another advanced trick until we get a good combined tool: for big point release isos that everyone will want, i can use zsync to setup the new file iso, then just stop and switch to bittorrent, which will actually well enough since it moves the existing pieces where they need to be in the iso.

edit: trying to find ubuntu server side process documentation but meanwhile client side debian builds of zsync for arm and others which should work in android afaik.
* https://packages.debian.org/sid/zsync

edit+1day: searched 15min while brain was properly awake and found ubuntu general infrastructure code with automated use of zsync, which probably looks more complex from all the checking if the build was properly finished first, etc.
* https://bazaar.launchpad.net/~ce-infrastructure/live-build/lb-sg-2.x/view/head:/scripts/build/lb_binary_zsync#L80
