### ISSUE TITLE
CMAudioFX also removes Lineage AudioFX

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#603]
I suggest that the keyword is changed so that it will not be described as limited to only removing AudioFX from CyanogenMod, but also removes AudioFX from other ROMs.

**Comment by FayneAldan** [comment]
The name `CMAudioFX` is because AudioFX originally came from CyanogenMod (actually from an [optional package](https://web.archive.org/web/20161015144228/https://cyngn.com/c-apps) made by Cyanogen for CM), hence why the package name is `org.cyanogenmod.audiofx` on all ROMs that include it. However, it's still the same app across all ROMs that include it (unless the app is outdated). It doesn't make any sense to have keywords for `CMAudioFX`, `LineageAudioFX`, `ResurrectionRemixAudioFX`, `AICPAudioFX`, etc. if they all do exactly the same thing. The same applies for `CMFileManager` (which still has the CM package name even though it's been updated for Lineage) and `CMMusic`.

**Comment by VincentJoshuaET** [comment]
I suggest that the keyword is change to only AudioFX to avoid confusion.

**Comment by darkmorpher** [comment]
Or add note on GApps, Aroma, and on the wiki about it.

**Comment by osm0sis** [comment]
It reads pretty clearly on the Advanced Options Wiki page.
