### ISSUE TITLE
Google Contacts are not syncing in any build except Pico

### ISSUE THREAD

**Issue by hemlok89** [opengapps/opengapps#653]
Hello, I have a Moto E Otus, running LineageOS 14.1 with OpenGapps Pico. For last few months, I have tried to flash Mini, Micro or even Aroma but in none of these builds Contacts are syncing from cloud. Only in the Pico build everything is working properly. First I thought of it as a effect of Magisk or Xposed, but did a cean install of nothing but ROM & Gapps & the same issue persists.

**Comment by sonya1st** [comment]
I hope this fixes it

**Comment by moore-bryan** [comment]
As of right now, **NO** gapps package--**none** of them, _nada_, _nil_--allows contacts to be synced on my Motorola g5+ (potter) on AEX, DU, Lineage, nor Omni _either_ set up as "new" or backing up from my Google account. _However_, PE--with built-in gapps--works just fine. This is _extremely_ frustrating because, frankly, I hate PE and would like to use a different rom...

**Comment by hemlok89** [comment]
@moore-bryan Just out of curiosity, are you using xposed framework while flashing the gapps?

**Comment by moore-bryan** [comment]
No Xposed; haven't used that since JB.

**Comment by mindflayer** [comment]
Same problem on a Xiaomi Mi Mix 2.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by andypillip** [comment]
I am seeing this issue on my Pixel 2 with Lineage 18.1 (20210824-nightly-walleye) and just sideloaded Open Gapps 20210825 (arm64 11) to check.

Anything I can do?

There is no error, the accounts app claims that contact details just synced, but the list is completely empty in Lineage's Contacts app and in Google's.

Thanks
