### ISSUE TITLE
Faceunlock installed but trusted face not available 

### ISSUE THREAD

**Issue by cheeserick** [opengapps/opengapps#684]
My system and device: OnePlus 5T, LineageOS 15.1 Official.
Opengapps: arm64 8.1 stock, 20181029.
You can find that facedetect and faceunlock were installed in my log but there is no Trusted Face in smart lock. And smart lock in trusted agents also enabled.
I have tried the Google face unlock module on magisk but failed.

[My gapps log](https://drive.google.com/file/d/1AYLB5bv8UEI5w0KfvwOg_tnzfcUG7JOD/view?usp=drivesdk)   

![Smart lock](https://i.imgur.com/oBGqoQb.png)
![Trusted agents](https://i.imgur.com/gjfPxJf.png)

**Comment by SpasilliumNexus** [comment]
Not an OpenGApps problem. Blame Google.

See: https://forum.xda-developers.com/showpost.php?p=77894229&postcount=5662
Other users confirmed in both that thread and on Telegram that it was fixed after.

**Comment by nikzhang2016** [comment]
@SpasilliumNexus Thank you but my 5T is with the latest google play services and the trust face app is avialable in /system while that option doesn't appear. And the issue you mentioned is resolved 5 months ago, is there any possibility that Google ignore the bug on some certain devices?

**Comment by SpasilliumNexus** [comment]
The workaround I've linked above was provided 14 days ago (October 16, 2018). That issue has been a thing for a while until it happened to me the same day I've made that post. Others with the same problem fixed it by installing 14.5.66 then seeing if it came back.

It hasn't been fixed because not enough users are using the feedback (via ROM Settings menu > Google > Question Mark icon > Send feedback) to report it. It would help if more users also send a tip to Android News sites such as Android Police about the issue, in hopes of it getting exposure.

**Comment by nikzhang2016** [comment]
@SpasilliumNexus Thanks bro, I have joined the beta program of Google play services and waiting for updates, wish it'll work.

**Comment by acras01** [comment]
I have the same problem but in my case it caused by misbehavior of FaceUnlock detection when installing gapps. My device is a-only PT supported and "android.hardware.camera.xml" is in /vendor/etc/permissions. But installer doesn't look there.
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/2561725/open_gapps_debug_logs.tar.gz)

**Comment by sonya1st** [comment]
On Oct 29, 2018 10:38 PM, Tommy <notifications@github.com> wrote:

The workaround I've linked above was provided 14 days ago (October 16, 2018). That issue has been a thing for a while until it happened to me the same day I've made that post. Others with the same problem fixed it by installing 14.5.66 then seeing if it came back.

It hasn't been fixed because not enough users are using the feedback (via ROM Settings menu > Google > Question Mark icon > Send feedback) to report it. It would help if more users also send a tip to Android News sites such as Android Police about the issue, in hopes of it getting exposure.
