### ISSUE TITLE
The mysterious stories of SetupWizard

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#7]
A plan about how/what about SetupWizard has to be done.
SetupWizard differs per phone and tablet nexus image.
Their versioncode, api level etc are the same, even their supported DPIs are (almost?) the same. Just within the package different DPI resources are available.
Maybe we can make a unified package from the resources of both??? Or some other creative solution?

**Comment by bgiesing** [comment]
From #88:
===
Currently, Tablets and Phones have two different Setup Wizards. Should we support both like TK? I think this might fix a bug that some (me included) have had, where the SetupWizard would crash Play services when skipping Tap N' Go as I haven't had an issue with the stock Nexus 7 2013's wizard which is what TK is offering.

## To integrate:
- [ ] Change Folder structure to accommodate both.
- [ ] Add `./add_sourceapp.sh` support to recognize these separate APKs.
- [ ] Upload both variants
- [ ] Add to update-binary to install them

**Comment by mfonville** [comment]
@dankoman30 did find that within resources.arsc the two versions differ.
The phone version contains "product=default" and tablets have "product=tablet" but since this are compiled and compressed resources fetching this string will be hard.

**Comment by dankoman30** [comment]
@mfonville you can just add apktool to your build tools for checking this value.

https://github.com/iBotPeaches/Apktool

run 'apktool d -s SetupWizard.apk' and then in the output folder, grep SetupWizard/res/values/strings.xml for the value.

this command won't take long because you're only decompiling the resources with the -s flag.

no need to go through framework installation for apktool, because you're only decompiling.
