### ISSUE TITLE
opengapps does not overwrite stock apps

### ISSUE THREAD

**Issue by iamprajot** [opengapps/opengapps#701]
installing opengapps after LineageOS does not overwrite the stock applications (Phone, Music etc.) and both exist at the same time and force closes each time.

**Comment by shuli81** [comment]
Can confirm this. 12/9 build did not remove stock phone.

**Comment by yurikoles** [comment]
Also, confirming (Super/Pie/ARM64). And `AOSPDialer` keyword doesn't remove it.

**Comment by iamprajot** [comment]
Yes previous builds used to replace the Stock apps but December builds don't replace Phone and Music.

**Comment by r3t3ch** [comment]
[This change](https://github.com/opengapps/opengapps/commit/0392c9cb249ce0584e5144143f6a9500941bed72#diff-4b4d756dd3b2a232970b47588e486eddR388) was made to prevent issue #672. This is pretty obnoxious since it completely disables the removal option for the sake of resolving an issue that likely only affected a small number of users. Disable auto removal on installation of google dialer, but don't disable the keyword.

**Comment by Crescendo-BLYAT** [comment]
> [This change](https://github.com/opengapps/opengapps/commit/0392c9cb249ce0584e5144143f6a9500941bed72#diff-4b4d756dd3b2a232970b47588e486eddR388) was made to prevent issue #672. This is pretty obnoxious since it completely disables the removal option for the sake of resolving an issue that likely only affected a small number of users. Disable auto removal on installation of google dialer, but don't disable the keyword.

how about the Lineage's Music app?
plue sometimes the Google Camera isn't installed....

**Comment by curiousrom** [comment]
> This is pretty obnoxious since it completely disables the removal option for the sake of resolving an issue that likely only affected a small number of users.

Yes it affects a small number of users making **EMERGENCY CALLS**.

So who cares if it could be a question of live or death for them. :innocent:

**Comment by iangabrielsanchez** [comment]
I'm still experiencing this.
