### ISSUE TITLE
gapps-config example [Need your Little Help]

### ISSUE THREAD

**Issue by hasanalizxc** [opengapps/opengapps#706]
I found this website https://opengapps.org/?api=7.1&variant=pico and flashed with TWRP..

It installed Google system base, Google Android Shared Services, Google Play Store, Google Calendar Sync, Dialer Framework, Google Package Installer (replaces stock/AOSP Package Installer), Google Play services and Google Text-to-Speech.

I tried to disable Google Play Service but no luck. I tried to uninstall but couldn't. Then wiped Cache, Dalvic and System partitions. Flashed ROM and worked, uninstalled.

Then i found this Github page and read about Advanced Options. He is saying; we can build our own gapps-config files with a script.

What i want?

I just want to install only Google Play Service and exclude all of them. Also i want to disable that service after installation.

Believe me i don't have knowledge about programming or scripting. For this reason i just ask your help..

Thank you so much.

P.S: My device is N910C and using LOS 14.1

Have a happy life with your loved ones.

**Comment by z2z** [comment]
I think this cannot be achieve using advance option. You might have too manually modify pico zip package.

Also explore microG & nanodroid.

**Comment by lss4** [comment]
The wiki contains information on how to exclude even things provided in pico. See Advanced Features and Options.

I never realized even with pico it was replacing things such as Dialer Framework and PackageInstaller with a Google counterpart until recently, and only just found out how to configure it to exclude even things provided by OpenGApps pico on the wiki.

I feel bad for myself for not realizing this sooner. My .gapps-config is like this. Since I'm using the pico package I didn't include the `PicoGApps` keyword. If you're using a larger variant, you can add this keyword as well.

```
Exclude

# Pico+
CalSync                 # Install Google Calendar Sync (if Google Calendar is being installed)
DialerFramework         # Install Dialer Framework (Android 6.0+)
GoogleTTS               # Install Google Text-to-Speech Engine (Micro+ on 5.0-, Pico+ on 6.0+)
PackageInstallerGoogle  # Install Package Installer (Android 6.0 only & Android 8.0+)
```

And here's a suggestion... Is it possible to provide an absolute minimum package (core-only flavor) that installs only the core package (like Play Store, Play Services) and that's it, without any advanced configuration? Not all users would be aware of the fact that even Pico is replacing system components.

And here's what I found regarding PackageInstallerGoogle (#223, #227). While it's barely noticeable, I sincerely don't want even these functionalities get infested by Google during the process.

After all, I'm only using it for Wear OS support as AW 2.0 watches can't work without it unlike AW 1.5 ones, and that microG hasn't supported it yet. Otherwise I'd have ditched GApps entirely a long time ago.
