### ISSUE TITLE
black screen trying to use Google Play (or adding my Google account)

### ISSUE THREAD

**Issue by teixedor** [opengapps/opengapps#724]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

After installing opengapps, the browser stopped working: complains about Webview which is not properly installed
And I'm not able to use Google Play: I'm getting a black screen after "session start"
I'm getting the same black screen when I try to add my google account.

**Reproduction Steps:**

I rooted my phone and installed a new ROM.

Browser was working correctly.

1. Factory reset and format /system
2. Install my ROM
3. Check that browser is working ok
4. Boot recovery-twrp-vernee_M5_3.1.1.img  (version 3.2.1 failed due to a bug)
5. delete microg* and nlp* directories
6. Install opengapps 
7. Wipe the Dalvik & cache
8. Check that browser stopped working (complains about Webview)
9. Check I can't neither use Google Play nor add my Google Account (black screen)

3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by muhAlantabli** [comment]
Any new News about this issue ?

**Comment by lss4** [comment]
Apparently OpenGApps by default attempted to delete WebViewGoogle if the folder is found. I experienced this on Sony XZ Premium 47.2.A.10.62 CN firmware. Previous versions used the folder "WebViewGoogle-full" to store stock WebView and were not affected by this.

You can try [disabling](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options) automatic deletion of stock WebView (and other apps) through .gapps-config.

The black screen is caused by OpenGApps deleted your stock firmware's original WebView implementation. Some stock ROMs (like mine) have a strict WebView validation that it won't accept anything else (even sideloaded Chrome). In such a situation, installing any package lesser than Stock would end up a broken system without any usable WebView.

Seriously GApps by default shouldn't really bother deleting stock WebView... it leads to all kinds of issues for users who're trying to flash lesser packages.

Honestly... after seeing all these "unwanted" default behaviors in the script I'm starting to lose trust in OpenGApps in overall... :-(

**Comment by jamuir** [comment]
Another way to avoid the webview issues is to add the following package-overlay to your ROM:

https://github.com/opengapps/aosp_build/tree/master/overlay/webview

There are some other ROM changes needed to make the opengapps zips work 100% correctly.  This could perhaps be communicated better.

**Comment by lss4** [comment]
In my case this occurred on stock ROM which we have no control of, and it's not possible to make sure all custom ROMs honor what OpenGApps expects, such as the overlay you mentioned.

Apparently the WebView should only be safe to delete if user explicitly specified to install Chrome (which is available on Stock and above). WebView should not be touched when Chrome is specified not to be installed, or when installing lesser packages like Nano and Pico which don't include Chrome. Otherwise, the system would end up broken without a usable WebView.

The script need to be corrected, otherwise lesser packages like Nano and Pico packages could end up dangerous as it would irreversibly delete the only usable WebView implementation on the system, effectively crippling it.

**Comment by sonya1st** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snsnsjsn** [comment]
unzip the opengapps.zip
edit install.sh
like this 
`# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs
removal_bypass_list="
";`

 to 
`# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs
removal_bypass_list="
WebViewGoogle
";`

then zip all
and copy into sdcard 
and use twrp flash into system
reboot

**Comment by lss4** [comment]
> unzip the opengapps.zip
> edit install.sh
> like this
> `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" ";`
> 
> to
> `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" WebViewGoogle ";`
> 
> then zip all
> and copy into sdcard
> and use twrp flash into system
> reboot

... Sorry for a late response but I personally don't think this should require a manual user intervention as some OpenGApps users would not touch the default configuration (creating the .gapps-config), not to mention manually modifying a flashable zip file has the risk of resulting in an unflashable zip due to various reasons (script errors, or simply the zip becomes unreadable by TWRP). It's a potentially unsafe issue that should have been corrected.

Not sure how it is now (whether or not the installation logic has been corrected), as now I'm using BiTGApps which supports Android 10 and is very minimal by default (does not contain anything I deem unwanted).

**Comment by systobe** [comment]
> 
> 
> unzip the opengapps.zip
> edit install.sh
> like this
> `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" ";`
> 
> to
> `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" WebViewGoogle ";`
> 
> then zip all
> and copy into sdcard
> and use twrp flash into system
> reboot

Worked for me, thanks for the instruction!

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by Trojblue** [comment]
Just wanted to comment that I tried to install `openGapps-arm64-7.0-nano-20201223` on my Xiaomi Mi pad 3, and encountered the same issue
There is no available webView to select from in the developer settings, after flashing the zip.
The solution was to download aroma pack, and select chrome

**Comment by lss4** [comment]
> Just wanted to comment that I tried to install `openGapps-arm64-7.0-nano-20201223` on my Xiaomi Mi pad 3, and encountered the same issue
> There is no available webView to select from in the developer settings, after flashing the zip.
> The solution was to download aroma pack, and select chrome

Haven't really took a notice about this issue since I switched to BiTGApps as that one works better with Android Q and onwards.

So it seems the issue is still reproducible. OpenGApps is still deleting existing WebView, if possible, on nano and pico packages which doesn't have Chrome included.

**Comment by aanyoti** [comment]
> unzip the opengapps.zip edit install.sh like this `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" ";`
> 
> to `# List of GApps files that should NOT be automatically removed as they are also included in (many) ROMs removal_bypass_list=" WebViewGoogle ";`
> 
> then zip all and copy into sdcard and use twrp flash into system reboot

Hi, I tried this but after editing and zipping the file, the installer in TWRP outputs it as an invalid zip....I noticed the archive property changed from UNIX,DOS to DOS only after I zipped it, could this be the issue?
