### ISSUE TITLE
could't install on Redmi Note 7(lavender)

### ISSUE THREAD

**Issue by OdinShiva** [opengapps/opengapps#738]

**Comment by Mattwmaster58** [comment]
Most custom ROMs for this device are arm64 based. The ROM that comes with the phone is arm based.
By default, you'll only be able to install the arm based gapps. But the custom ROMs need the arm64 based gapps, which won't install because opengapps thinks you are running an arm based ROM. For this reason, most custom ROMs will provide a download link to a modified arm64 gapps that will install.

**Comment by lbdroid** [comment]
My observation actually is that the wrong architecture error tends to be related to not being able to find the unzip command in the expected path. In particular, unzip is often installed to /system/bin/, but opengapps looks at /system/xbin/ for it.

opengapps actually checks the architecture based on the installed system image, not based on the hardware itself.
