### ISSUE TITLE
Unable to unlock encrypted device after Lineage OTA with Super/Pie

### ISSUE THREAD

**Issue by yurikoles** [opengapps/opengapps#749]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

**Issue description:**

GApps removes stock keyboard, which breaks OTA on encrypted device.

1. Install Super GApps on LOS 16.
2. Enable device encryption.
3. Install OTA via official LOS updater.

**Expected behavior:**

GApps detects that device is encrypted and keeps stock keyboard.

**Observed behavior:**

Unable to unlock device because there is no keyboard after OTA.

**Comment by Crescendo-BLYAT** [comment]
this is reported by @luk1337 & fixed by @NicholasBuse already... 
it was missing the required permission....

https://github.com/opengapps/opengapps/issues/748

**Comment by yurikoles** [comment]
Are you sure you had linked correct issue?

**Comment by Crescendo-BLYAT** [comment]
> Are you sure you had linked correct issue?
**Observed behavior: Unable to unlock device because there is no keyboard after OTA.**

Read the linked issue: it's preventing boot when secure startup is used...
My problem was exactly the same: no keyboard is being presented during secure boot, unable to input anything.

It **was't** bcoz of the AOSP keyboard being deleted ot replaced with Gboard. The missing permission prevented it from being displayed.

When AOSP Keyboard is replaced by Gboard, Gboard will be displayed for inputting the secure boot PIN/password.

**Comment by Crescendo-BLYAT** [comment]
Also I use Super with LOS 16.
OTA is prefectly OK on both of my devices - Mi 5s Plus - Nightly LOS 16.
