### ISSUE TITLE
These is no Android 8.0 (Oreo) Stock version release?

### ISSUE THREAD

**Issue by alexceltare2** [opengapps/opengapps#779]
I couldn't find it anywhere because I need to flash it on a phone that has only partial Google Play support and I'm afraid the "full" version will create duplicate apks, unlike the stock variant that deletes already existing apks.

**Comment by alexceltare2** [comment]
On the same note, the Super version is also missing.

**Comment by nezorflame** [comment]
The script for the apps removal should work regardless of the variant.
On that note, `stock` and `super` variants are there now (I assume they were missing only for 1 release due to a broken build):
<img width="367" alt="изображение" src="https://user-images.githubusercontent.com/3906766/68197932-2b841b00-ffcc-11e9-81de-a74cd86dd9c3.png">
<img width="345" alt="изображение" src="https://user-images.githubusercontent.com/3906766/68197948-3474ec80-ffcc-11e9-882d-1d07a7875ee4.png">

**Comment by nezorflame** [comment]
@alexceltare2 next time when this happens, make sure to check the `OLDER RELEASES` link on the website to check older packages, both `stock` and `super` variants should always be there for 8.0.

**Comment by nezorflame** [comment]
@mfonville @NicholasBuse this can be closed now.

**Comment by alexceltare2** [comment]
WTF!? Why did you close this issue? It is not resolved! I searched in old releases and current and I can assure you that there is NO 8.0 STOCK RELEASE for either ARM or ARM64. I click the download button and there is no download. I get redirected to the sourceforge page and there is no `8.0-stock` or `8.0-super` variant. Don't believe me? see for yourself:
![ggg](https://user-images.githubusercontent.com/7403035/68207787-9e3ec780-ffc7-11e9-9fbd-7162b5aea484.png)

**Comment by nezorflame** [comment]
@alexceltare2 no need to worry - I was mistaken, sorry about that.
Currently the website relies on the `LATEST.json` file ([example for arm64](https://github.com/opengapps/arm64/blob/master/LATEST.json)) to judge if the package is present in the latest release. Curerntly both `stock` and `super` are listed as available, which is a bug.

@mfonville please reopen this. We need either to:
- enable builds for the `stock` and `super` variants of the 8.0 version
- remove these options from the `LATEST.json` files for the `8.0` if we don't plan to build them (not sure why though)

**Comment by mfonville** [comment]
Sorry for closing this bug in error.
I checked the buildbot logs and it shows that these builds fail because of:
```
ERROR: No fallback available. Failed to build framework com.google.vr.platform.jar
```
so apparently this package is missing, even though it is defined in the ruleset
@NicholasBuse @nezorflame can you have a look at the files and the scripts and figure out what has to be changed?

**Comment by mfonville** [comment]
This should fix the issue: https://github.com/opengapps/opengapps/commit/ef8b34d03354012db7367026ed525a60cbd5b2f1
