### ISSUE TITLE
Feature request: Lineage 17.1 recovery support

### ISSUE THREAD

**Issue by rhansen** [opengapps/opengapps#834]
Sideloading Open GApps via Lineage 17.1 recovery silently fails; see https://gitlab.com/LineageOS/issues/android/-/issues/1894

TWRP is not available for all devices supported by Lineage 17.1 (Essential PH-1 in particular), so support for Lineage's own recovery would be nice.

**Comment by nezorflame** [comment]
AFAIK this should already be supported, thanks to the @osm0sis.

**Comment by osm0sis** [comment]
It's supported in up-to-date builds as far as I know, @aleasto has both confirmed this before. We're also aware of some issues with addon.d on dynamic/logical partition devices, but these seem to be an issue with backuptool/addon.d-v2 as a whole, since Open GApps isn't doing anything special - just doing normal backup/restore.

**Comment by aleasto** [comment]
This is limited to mata and fixed by https://review.lineageos.org/c/LineageOS/android_system_core/+/274794

**Comment by rhansen** [comment]
Cool, thanks!
